(function(p,g){p.namespace("dockingmenu");p.ncDock=function(){return{options:{size:48,sizeMax:0,capSizing:0,distance:72,coefficient:1.5,duration:200,align:"right",labels:!0,labelShow:!1,source:0,loader:0,inactivity:0,fadeIn:0,fadeLayer:"",step:50,setLabel:0,flow:0,idle:0,onReady:0,onSleep:0,onWake:0,noBuffer:0,active:-1,bias:50,noAntiFlutter:0},nextId:0,useJqLoader:"opera"==p.agent.browser||"safari"==p.agent.browser,init:function(a){var b=g(a),c=DATA(b),e=c.Opts,f=VERTHORZ[e.vh],d=VERTHORZ[f.inv],
t=c.Border,k=e.fadeLayer,m=e.labels,r=c.ElCt,v=g("<div/>"),A=g("<ul/>"),w=0,q=0,l,h,z,u;REMOVE_TEXT(a);for(b.children().each(function(a,b){c.Elem[a].Wrap=g(b).wrap(g("<li/>").append(g("<div/>"))).parent()});q<r;)h=c.Elem[q++],l=h.Pad,u=KEEP_PROPORTION(h,e.size,d,e.capSizing),h.Major=h.Final=h.Initial=u[f.wh],h.Item=h.Wrap.css(u).parent(),p.ncDock.options.labelShow&&h.img.attr({alt:""}).parent("a").andSelf().removeAttr("title"),c[d.wh]=Math.max(c[d.wh],e.size+l[d.lead]+l[d.trail]),h.Offset=w,h.Centre=
w+l[f.lead]+h.Initial/2,w+=h.Initial+l[f.lead]+l[f.trail];for(q=0;q<r;)for(z in h=c.Elem[q++],l=h.Pad[f.lead]+h.Pad[f.trail],c.Spread+=h.Initial+l,{Centre:1,Offset:1}){SET_SIZES(c,h[z]);w=0;for(d=r;d--;)w+=c.Elem[d].Final+l;w>c[f.wh]&&(c[f.wh]=w)}for(;q;)h=c.Elem[--q],h.Final=h.Initial;b.wrapInner(v.addClass(n[6]).append(A.attr({id:c.Id,"class":n[8],style:""})));f=c.Yard=g("#"+c.Id);for(d=4;d--;)t[d]=AS_INTEGER(f.css("border"+y[d]+"Width"));for(t=f.parent().width(c.width+t[1]+t[3]).height(c.height+
t[0]+t[2]);q<r;)h=c.Elem[q],l=h.Item,CHANGE_SIZE(c,q,h.Final,!0),l.addClass(n[1]),h.img.addClass(n[2]+q),l=h.Label,l.el=p.ncDock.options.labelShow?g("<div/>").css({position:"absolute",margin:0}).addClass(n[3]+" "+n[3]+h.Link).insertAfter(h.img).hide().on("click",LABEL_CLICK):g("<div/>").css({position:"absolute",margin:0}),m&&(v="b"===m.charAt(0),A="r"===m.charAt(1),l.el.css({top:v?"auto":0,left:A?"auto":0,bottom:v?0:"auto",right:A?0:"auto"})),h=e.setLabel.call(a,h.Title,q,l.el[0]),!1!==h&&g("<div/>").addClass(n[3]+
"text").html(h.toString()).appendTo(l.el),++q;h=b.on(CUSTOMEVENTS.join(" "),LISTENER);f.on(MOUSEEVENTS.join(" "),x[1],MOUSE_HANDLER).find("*");c.Elem[e.active]&&DO_MOUSE(0,c,e.active,2);c.Asleep=!1===e.onReady.call(a,"ready");c.Asleep||(k?("menu"!==k&&(h="dock"===k?f:t),c.Asleep=!!g(x[8]+","+x[6],h).addClass(n[4]).css({filter:"inherit"}),h.css({opacity:0}),REVEAL_MENU(b),h.animate({opacity:1},e.fadeIn,function(){var a=MENU_OR_ITEM(this);DATA(a).Asleep=!g(x[4],this).add(this).css({filter:""}).removeClass(n[4]);
a.trigger("dockshow",["ready"]).trigger(CUSTOMEVENTS[0])})):(REVEAL_MENU(b),b.trigger("dockshow",["ready"]),SET_IDLER(c)))},convert:function(a){return CONVERT_LISTS.call(g(a).get(0))}}}();var y=["Top","Right","Bottom","Left"],B=["Major","Minor"],n=[],x=p.map("docking-menu-pnl docking-menu-item docking-menu-image docking-menu-label docking-menu-filter state-hover docking-menu-wrap docking-menu-list docking-menu-group".split(" "),function(a,b){n[b]=""+a;return"."+n[b]});DATA_NAMES=["dockingmenu","dockingmenu_conv",
"dockingmenu_li","dockingmenu_list"];MOUSEEVENTS=["mouseenter","mousemove","mouseleave"];CUSTOMEVENTS=["docknudge","dockidle","dockfreeze"];TIMERS=["Idler","Inactive","Indock","Overdock","Offdock"];VERTHORZ={v:{wh:"height",xy:1,tl:"top",lead:0,trail:2,inv:"h"},h:{wh:"width",xy:0,tl:"left",lead:3,trail:1,inv:"v"}};XY=[0,0];WIN_TIMEOUT=window.setTimeout;DATA=function(a){return a.data(DATA_NAMES[0])};FALSEFUNC=function(){return!1};ITEM_INDEX=function(a){return g(a).parent().children(x[1]).index(a)};
KEEP_PROPORTION=function(a,b,c,e){var f={},d=VERTHORZ[c.inv].wh;e=!e||a[c.wh]>b;f[c.wh]=e?b:a[c.wh];f[d]=e?Math.round(b*a[d]/a[c.wh]):a[d];return f};MENU_OR_ITEM=function(a,b){return g(a).closest(x[b||0])};NAMESPACED_DATA=function(a){var b={},c,e;for(c in a)(e=c.match(/^dockingmenu([A-Z])([a-zA-Z]+)jq/))&&(b[e[1].toLowerCase()+e[2]]=a[c]);return b};AS_INTEGER=function(a){a=parseInt(a,10);return isNaN(a)?0:a};CLEAR_TIMER=function(a,b){for(var c=TIMERS[b]?b+1:TIMERS.length;b<c&&c--;)a[TIMERS[c]]&&(window.clearTimeout(a[TIMERS[c]]),
a[TIMERS[c]]=null)};CONVERT_LISTS=function(){var a=g(this),b=a.attr("id")||"",c=a.data(DATA_NAMES[1]),e=a.children("li").map(function(){var a=g("img",this).eq(0),c=a.parent("a");return c.length?a.siblings().length?null:c[0]:a.get(0)}),f=b?{id:b}:{},d;if(!a.length||!e.length)return this;if(c)return c;if(d=a.attr("style"))f.style=d;d=g("<div/>").addClass(n[7]).data("dockingmenu",g.extend({},a.data("dockingmenu"),NAMESPACED_DATA(a.data()))).data(DATA_NAMES[3],{el:this,attr:f});a.hide().removeAttr("id");
e.each(function(){g(this).data(DATA_NAMES[2],g("<img/>").insertBefore(this)[0]).appendTo(d)});d.attr("id",b).insertBefore(a);a.data(DATA_NAMES[1],d[0]);return d[0]};GET_TIME=function(a){var b=g.now();a=a?a.Stamp+a.Opts.duration:0;a>b&&(b-=a-b);return b};IMAGE_ONLOAD=function(a){var b=a.data;a=DATA(g(b.menu));var c,e;a&&(c=a.Elem[b.idx],e=a.Opts,e.sizeMax?g.extend(c,KEEP_PROPORTION(this,e.sizeMax,VERTHORZ[VERTHORZ[e.vh].inv]),e.capSizing):(c.width=this.width,c.height=this.height),--a.Load||WIN_TIMEOUT(function(){p.ncDock.init(b.menu)},
0))};ITEM_EXPANSION=function(a,b,c){b.Item.toggleClass(n[5],!c);a.Menu.trigger("docking-menu-item",[b.img[0],!c])};LABEL_CLICK=function(){g(this).prev("img").triggerHandler("click")};LABEL_SHOW=function(a,b){var c=a.Elem[a.Current];c&&a.Opts.labels&&p.ncDock.options.labelShow&&c.Label.el.toggle(!!b)};RELATIVE_XY=function(a){var b=VERTHORZ[a.Opts.vh],c=-1,e=XY[b.xy]-a.Elem[0].Item.offset()[b.tl],f,d,g,k;if(0<=e)for(f=0;0>c&&f<a.ElCt;f++)d=a.Elem[f],g=d.Pad[b.lead]+d.Pad[b.trail],k=d.Major+g,e<k?(f!==
a.Current&&(LABEL_SHOW(a),a.Current=f),c=d.Offset+e*(d.Initial+g)/k):e-=k;return c};REMOVE_TEXT=function(a){for(var b=a.childNodes.length,c;b;)c=a.childNodes[--b],(c.childNodes||[]).length?REMOVE_TEXT(c):3===c.nodeType&&a.removeChild(c)};REVEAL_MENU=function(a){a.css({visibility:"visible"}).show()};SET_IDLER=function(a){var b=a.Opts.idle;b&&(CLEAR_TIMER(a,0),a[TIMERS[0]]=WIN_TIMEOUT(function(){a.Menu.trigger(CUSTOMEVENTS[1])},b))};SET_SIZES=function(a,b){var c=a.Opts,e=VERTHORZ[c.vh].wh,f=a.ElCt,
d,g,k;for(b=b||0===b?b:RELATIVE_XY(a);f--;)d=a.Elem[f],k=d.Initial,0<=b&&(g=Math.abs(b-d.Centre),g<c.distance&&(k=d[e]-Math.round((d[e]-d.Initial)*Math.pow(g,c.coefficient)/c.attenuation)),f!==a.Current||c.noAntiFlutter||(g=[XY[VERTHORZ[c.vh].xy],a.Current,k].join(),g===a.ToFro[0]&&k!==a.ToFro[2]?k=a.ToFro[2]:a.ToFro=[a.ToFro[1],g,k])),d.Final=k};TRANSFORM_LABEL=function(a,b,c){return a};CHANGE_SIZE=function(a,b,c,e){var f=a.Elem[b],d=a.Opts,p=a.Yard,k=a.Border,m=VERTHORZ[d.vh],r=VERTHORZ[m.inv],
v=d.labels,n=a.Elem[a.Current],w=f.src!==f.altsrc,q,l,h,z,u,x;if(e||f.Major!==c){q=g.boxModel||"v"===d.vh?0:k[m.lead]+k[m.trail];e||f.Major!==f.Initial||(w&&(f.img[0].src=f.altsrc),ITEM_EXPANSION(a,f));a.Spread+=c-f.Major;l=KEEP_PROPORTION(f,c,m);h=d.size-l[r.wh];u={middle:1,center:1,top:2,left:2}[d.align]||0;1<u?l["margin"+y[r.trail]]=h:u?(z=Math.round(h*(100-d.bias)/100),l["margin"+y[r.lead]]=h-z,l["margin"+y[r.trail]]=z):l["margin"+y[r.lead]]=h;if(c!==f.Major||e&&!b){if(d.flow)p.parent()[m.wh](a.Spread+
k[m.lead]+k[m.trail]);p[m.wh](a.Spread+q)}f.Wrap.css(l);d.flow||p.css(m.tl,Math.floor(Math.max(0,(a[m.wh]-a.Spread)/2)));if(a.OnDock){if(n&&v){b=n.Label;d=b.el;if(b.mc)for(u in b.mc=0,VERTHORZ)for(x in b[u]=d[VERTHORZ[u].wh](),{lead:1,trail:1})b[u]+=AS_INTEGER(d.css("padding"+y[VERTHORZ[u][x]]));"m"===v.charAt(0)&&d.css({top:Math.floor((n[B[r.xy]]-b.v)/2)});"c"===v.charAt(1)&&d.css({left:Math.floor((n[B[m.xy]]-b.h)/2)})}a.Stamp||LABEL_SHOW(a,1)}f.Major=c;f.Minor=l[r.wh];e||c!==f.Initial||(w&&(f.img[0].src=
f.src),ITEM_EXPANSION(a,f,1))}};FACTOR_SIZES=function(a){var b=a.Opts,c=VERTHORZ[b.vh],e=b.duration+b.step,f,d;a.Stamp&&(e=GET_TIME()-a.Stamp,e>=b.duration&&(a.Stamp=0));if(e>=b.step){d=(b.duration-e)/b.step;for(b=0;b<a.ElCt;b++)e=a.Elem[b],f=(f=e.Final-e.Major)&&1<d?e.Major+Math[0>f?"floor":"ceil"](f/d):e.Final,CHANGE_SIZE(a,b,f);a.Spread>a[c.wh]&&(a.Yard.parent()[c.wh](a.Spread+a.Border[c.lead]+a.Border[c.trail]),a[c.wh]=a.Spread)}};IN_DOCK=function(a,b){var c=a.Elem,e=c.length;CLEAR_TIMER(a,2);
if(a.OnDock&&!a.Stamp){for(SET_SIZES(a,b);e&&c[e-1].Major===c[e-1].Final;)--e;e?(FACTOR_SIZES(a),a[TIMERS[2]]=WIN_TIMEOUT(function(){IN_DOCK(a,b)},a.Opts.step)):LABEL_SHOW(a,1)}};OFF_DOCK=function(a,b){var c=a.Elem,e=c.length;if(!a.OnDock){for(;e&&c[e-1].Major<=c[e-1].Initial;)--e;RELATIVE_XY(a);if(e)FACTOR_SIZES(a),a[TIMERS[4]]=WIN_TIMEOUT(function(){OFF_DOCK(a,b)},a.Opts.step);else{a.Stamp=0;for(e=c.length;e--;)c[e].Major=c[e].Final=c[e].Initial;a.Current=-1;b||SET_IDLER(a)}}};OVER_DOCK=function(a,
b){var c=a.Elem,e=c.length;if(a.OnDock){for(SET_SIZES(a,b);e&&c[e-1].Major===c[e-1].Final;)--e;e&&a.Stamp?("8.0"==p.agent.version&&(a.Stamp=0),FACTOR_SIZES(a),a[TIMERS[3]]=WIN_TIMEOUT(function(){OVER_DOCK(a,b)},a.Opts.step)):(a.Stamp=0,IN_DOCK(a,b))}};DO_MOUSE=function(a,b,c,e){var f=b.Elem,d=f.length;0===a&&(b.OnDock=1,0<=b.Current&&b.Current!==c&&LABEL_SHOW(b),b.Current=c,b.Stamp=e&&1<e?0:GET_TIME(b),OVER_DOCK(b,e?f[c].Centre:null));1===a&&(c!==b.Current&&(LABEL_SHOW(b),b.Current=c),IN_DOCK(b));
if(2===a){CLEAR_TIMER(b,1);b.OnDock=0;LABEL_SHOW(b);for(b.Stamp=GET_TIME(b);d--;)f[d].Final=f[d].Initial;OFF_DOCK(b,!!e)}};MOUSE_HANDLER=function(a){var b=DATA(MENU_OR_ITEM(this)),c=ITEM_INDEX(this),e=-1,f;b&&(b.Asleep?b.Opts.noBuffer||(b.Doze={El:this,type:a.type,pageX:a.pageX,pageY:a.pageY}):(f=b.OnDock,CLEAR_TIMER(b,0),XY=[a.pageX,a.pageY],a.type===MOUSEEVENTS[2]?f?e=2:SET_IDLER(b):(b.Opts.inactivity&&(CLEAR_TIMER(b,1),b[TIMERS[1]]=WIN_TIMEOUT(function(){DO_MOUSE(2,b,c,1)},b.Opts.inactivity)),
a.type===MOUSEEVENTS[1]?0>c?f&&0<=b.Current&&(e=2):e=!f||0>b.Current?0:1:0<=c&&!f&&(e=0)),b.Doze=null,0<=e&&DO_MOUSE(e,b,c)))};LISTENER=function(a){var b=g(this),c=DATA(b),e=a.type===CUSTOMEVENTS[2],f=e?"freeze":"sleep";c&&(a.type===CUSTOMEVENTS[0]?(f=c.Frozen?"thaw":"wake",c.Asleep&&(c.Asleep=!1===c.Opts.onWake.call(this,f),c.Asleep||(c.Frozen=!b.trigger("dockwake",[f]))),c.Asleep||(SET_IDLER(c),(b=c.Doze)&&MOUSE_HANDLER.call(b.El,b))):(CLEAR_TIMER(c,0),a=!c.Asleep||e&&!c.Frozen,a&&!1===c.Opts.onSleep.call(this,
f)||(c.Asleep=!CLEAR_TIMER(c,e?-1:1),c.Frozen=c.Frozen||e,a&&b.trigger("docksleep",[f]),e?c.Stamp=c.OnDock=0:DO_MOUSE(2,c,0,1))))};p.widget.dockingmenu=p.widget.Base.extend({init:function(a,b){this.setName("dockingmenu");this._super();var c="#"+b.id,e=naw(c),f=this._getTemplate(a),f=jQuery.extend({},p.ncDock.options,f),d="",n=p._getFixedUri(p.config.theme.basePath)+"/"+naw.config.theme.baseName+"/image/docking-menu-";if(!f.items){for(var k=g(c).children(),m=0;m<k.length;m++){var r=k[m].id,v=g(k[m]).text(),
d=d+"<li><img",d=d+(" id='"+r+"'");f.labelShow&&(d+=" alt=''");d+=" title='"+v+"'";d+=" src='"+n+r.toLowerCase()+".png'";d+="/></li>"}p(k).remove();p(c).append(d)}else if(f.items){for(m=0;m<f.items.length;m++)d+="<li><img ",d+=" id='"+f.items[m].id+"'",f.labelShow&&(d+=" alt='' "),d+=" title='"+f.items[m].title+"'",d+=" src='"+n+f.items[m].id.toLowerCase()+".png'",d+="/><li>";p(c).append(d)}this._create(e,f)},_create:function(a,b){return a=a.jq.map(CONVERT_LISTS).filter(function(){var a=g(this).children();
return!MENU_OR_ITEM(this).length&&a.length&&!a.not("img").filter(function(){return 1!==g(this).children("img").parent("a").children().length}).length}).each(function(){var a=g(this).addClass(n[0]),e=g("img",a),f={Menu:a,Id:n[8]+p.ncDock.nextId++,Elem:[],OnDock:0,Stamp:0,width:0,height:0,Spread:0,Border:[],Opts:g.extend({},b,a.data("dockingmenu"),NAMESPACED_DATA(a.data()),b||{}),Current:-1,Load:e.length,ElCt:e.length,ToFro:["","",0],Style:a.attr("style")},d=f.Opts,t,k;for(k in{size:1,distance:1,duration:1,
inactivity:1,fadeIn:1,step:1,idle:1,active:1,sizeMax:1})d[k]=AS_INTEGER(d[k]);k=1*d.coefficient;d.coefficient=isNaN(k)?1.5:k;if(t={middle:1,center:2}[d.align])k=AS_INTEGER(d.bias),1>k&&(d.align=2>t?"top":"left"),99<k&&(d.align=2>t?"bottom":"right"),d.bias=k;d.labels&&!/^[tmb][lcr]jq/.test(d.labels.toString())&&(d.labels={top:"br",left:"tr"}[d.align]||"tl");d.setLabel||(d.setLabel=TRANSFORM_LABEL);d.fadeLayer=d.fadeIn?{dock:1,wrap:1}[d.fadeLayer]?d.fadeLayer:"menu":"";for(k in{onSleep:1,onWake:1,onReady:1})d[k]||
(d[k]=!1===d[k]?FALSEFUNC:g.noop);t=/^m|cjq/.test(d.labels);d.attenuation=Math.pow(d.distance,d.coefficient);d.vh={left:1,center:1,right:1}[d.align]?"v":"h";a.data(DATA_NAMES[0],f);e.each(function(b,c){var e=g(c),k=e.parent("a"),m=k.attr("title")||"",q={},l,h,n;for(l in{src:1,alt:1,title:1,style:1})q[l]=e.attr(l)||"";q.src==naw.config.theme.basePath+"/"+naw.config.theme.baseName+"/image/docking-menu-.png"&&(q.src=naw.config.theme.basePath+"/"+naw.config.theme.baseName+"/image/docking-menu-glass.png");
n=(d.source?d.source.call(c,b):"")||e.data("dockingmenuAltsrc")||""||(/\.(gif|jpg|jpeg|png)jq/i.test(q.alt||"")?q.alt:"")||q.src;f.Elem[b]={img:e,src:q.src,altsrc:n,Title:q.title||m||"",Orig:{i:g.extend({},q),a:{title:m,style:k.attr("style")||""}},Label:{mc:t},Pad:[],Link:k.length?"link":"image"};for(l=4;l--;)f.Elem[b].Pad[l]=AS_INTEGER(e.css("padding"+y[l]));(d.loader?"jquery"===d.loader:p.ncDock.useJqLoader)?g("<img>").on("load",{idx:b,menu:a[0]},IMAGE_ONLOAD).attr({src:n}):(h=new Image,h.onload=
function(){IMAGE_ONLOAD.call(this,{data:{idx:b,menu:a[0]}});h.onload="";h=null},h.src=n)})}).end()}});p._addWidget("dockingmenu",p.widget.dockingmenu)})(naw,jQuery);