(function(m,f){ncMegaMenu=new function(){var k=null;f('<div class="sub-menu-pnl" style="position:absolute;top:0;left:0;display:none;"></div>');var v=f("<ul ></ul>")[0],n=f('<li style="position:relative;"></li>')[0],h=null,d=[];this.init=function(a){k=this;this.options=this._getOptions(a);a=f(this.options.renderTo);this._create(a,this.options)};this._create=function(a,c){if("xml"==c.type)null!=c.systemMenu?f.get(c.systemMenu,function(a){k._loadXml(c,a)}):self._loadXml(c);else if("json"==c.type){var g=
null,g=[],e=null;if(c.useBizMenu)e=c.useBizJsonMenu;else for(var b=0;b<c.userMenu.length;b++)g[b]=m.getRemoteFile(c.userMenu[b],!1),g[b]=m.convertObject(g[b]),null==e?e=g[b]:f.merge(e,g[b]);g=e;b=z(e,"\t",c);b=naw.parseXML(b);$xmlMenu=m(b.documentElement);null!=c.systemMenu&&(b=m.getRemoteFile(c.systemMenu,!1),b=m.convertObject(b),f.merge(e,b));k._loadJSON(c,e,g)}};this._getOptions=function(a){var c={offsetTop:0,offsetLeft:0,renderTo:"",ulTarget:"menuone",type:"xml",userMenu:"../../menu/menu_demo.xml",
systemMenu:"../../menu/menu_system.xml",menuone:"",targetId:"",onComplete:null,onOpen:null,onClose:null,showDelay:100,hideDelay:100,hoverOpenDelay:0,menus:[],dynamicEffect:"slide",addExpando:!1,onClick:null,onShowClick:!1,copyClassAttr:!1};return c=f.extend({},c,a)};this._MenuCollection=function(a){this.menus=[];this.init=function(a){if(a&&a.length)for(var c=0;c<a.length;c++)this.addMenu(a[c]),a[c].menuCollection=this};this.addMenu=function(a){a instanceof k._Menu&&this.menus.push(a);"json"==a.options.type&&
(a.options.menus.push(a),this.menus=a.options.menus);a.menuCollection=this;var c=this;f(a.target).hover(function(){if(!a.visible)for(var e=0;e<c.menus.length;e++)if(c.menus[e].visible){c.menus[e].hide();a.show();break}},function(){})};this.init(a)};this._Menu=function(a,c,g){this.menuItems=[];this.subMenus=[];this.active=this.visible=!1;this.parentMenuItem=null;this.settings=f.extend({},this.options,g);this.target=a;this.openTimer=this.menuCollection=this.timer=this.$eUL=this.$eDIV=null;this.path=
"";this.options=g;this.init=function(){if(this.target){if(this.target instanceof k._MenuItem)this.parentMenuItem=this.target,this.target=this.target.$eLI;else if("xml"==this.options.type||"json"==this.options.type)this.target=f(this.options.renderTo).find("#"+this.options.targetId).get(0);d.push(this);this.$eUL=f(v.cloneNode(1));this.parentMenuItem?this.parentMenuItem.$eLI[0].appendChild(this.$eUL[0]):this.target.appendChild(this.$eUL[0])}};this.addItem=function(a){a instanceof k._MenuItem?-1==f.inArray(a,
this.menuItems)&&(this.$eUL[0].appendChild(a.$eLI[0]),this.menuItems.push(a),a.parentMenu=this,a.subMenu&&this.subMenus.push(a.subMenu)):this.addItem(new k._MenuItem(a,this.settings))};this.addItems=function(a){for(var b=0;b<a.length;b++)this.addItem(a[b])};this.init();c&&c.constructor==Array&&this.addItems(c)};this._MenuItem=function(a,c){"string"==typeof a&&(a={src:a});this.src=a.src||"";this.url=a.url||null;this.urlTarget=a.target||null;this.addClass=a.addClass||null;this.data=a.data||null;this.subMenu=
this.parentMenu=this.$eLI=null;this.settings=f.extend({},this.options,c);this.active=!1;this.enabled=!0;this.separator=!1;this.objLi=a.objLi;this.options=c;this.init=function(){var a,c=this.src;this.$eLI=f(n.cloneNode(1));this.addClass&&this.$eLI[0].setAttribute("class",this.addClass);this.settings.addExpando&&this.data&&(this.$eLI[0].menuData=this.data);if(""==c)this.$eLI.addClass("menu-separator"),this.separator=!0;else{if((a="string"==typeof c)&&this.url)c=f('<a href="'+this.url+'"'+(this.urlTarget?
'target="'+this.urlTarget+'"':"")+">"+c+"</a>");else if(a||!c.length)c=[c];for(a=0;a<c.length;a++)if("string"==typeof c[a]){var b="<a";if("xml"==this.options.type){var d=this.objLi.attr("page"),h=this.objLi.attr("menuId"),k=this.objLi.attr("menuTitle"),q=this.objLi.attr("keyTitle"),l=this.objLi.attr("auth"),t=this.objLi.attr("visible"),p=this.objLi.attr("extra"),b=b+(" page='"+d+"'"),b=b+(" id='"+h+"'"),b=this.options.useTitle?b+(" title='"+this.objLi.attr(this.options.useTitle)+"'"):b+(" title='"+
k+"'"),b=b+(" keyTitle='"+q+"'");"undefined"!=typeof l&&(b+=" auth='"+l+"'");"undefined"!=typeof t&&(b+=" visible='"+t+"'");"undefined"!=typeof p&&(b+=" extra='"+p+"'");b+=">"+k+"</a>"}else"json"==this.options.type&&(d=this.objLi.page,h=this.objLi.menuId,k=this.objLi.menuTitle,q=this.objLi.keyTitle,l=this.objLi.auth,t=this.objLi.visible,p=this.objLi.extra,b+=" page='"+d+"'",b+=" id='"+h+"'",b=this.options.useTitle?b+(" title='"+this.objLi[this.options.useTitle]+"'"):b+(" title='"+k+"'"),b+=" keyTitle='"+
q+"'","undefined"!=typeof l&&(b+=" auth='"+l+"'"),"undefined"!=typeof t&&(b+=" visible='"+t+"'"),"undefined"!=typeof p&&(b+=" extra='"+p+"'"),b+=">"+k+"</a>");"undefined"!=typeof t&&"false"==t&&jQuery(this.$eLI[0]).hide();this.$eLI[0].innerHTML=b}else this.$eLI[0].appendChild(c[a].cloneNode(1))}};this.init();a.subMenu&&new k._Menu(this,a.subMenu,options)};this._loadXml=function(a,c){f.get(a.userMenu,{},function(g){$xmlMenu=m(g.documentElement);var e=null;if(c){var e=c.childNodes,b=parseInt(m.agent.version,
10);if(window.ActiveXObject&&9>=b)for(e=e[1].childNodes,b=0;b<e.length;b++)g.documentElement.appendChild(e[b].cloneNode(!0));else for(e=c.childNodes[0],b=0;b<e.childNodes.length;b++)e.childNodes[b].childNodes.length&&("safari"===m.agent.browser?g.documentElement.appendChild(g.importNode(e.childNodes[b],!0)):g.documentElement.appendChild(e.childNodes[b]));var d=a.ulTarget;a.menuone='<ul id="'+d+'" class="menu-root">';k._menuBarFromXML(a,m(g.documentElement))}else f("Menu",g).each(function(b){0==b&&
(a.menuone='<ul id="'+a.ulTarget+'" class="menu-root">',k._menuBarFromXML(a,m(this)))});g=A(g,"",!0);g=m.replace(g,'"@','"');var e=window.eval("["+g+"]"),e=e[0].Menu.MenuItem,h=function(a){for(var b=[],c=0;c<a.length;c++){var g={},e=a[c],d;for(d in e)"Menu"==d?e.Menu.MenuItem?g.Menu=e.Menu.MenuItem&&e.Menu.MenuItem.length?h(e.Menu.MenuItem):[e.Menu.MenuItem]:g[d]=e[d]:g[d]=e[d];b[c]=g}return b},e=h(e);f("ul#"+d+"> li > a").click(function(b,c){var g=f(this).attr("id");f("ul#"+d+"> li").each(function(a,
b){g!=f(this).attr("id")?f("> a",this).removeClass("state-current"):f("> a",this).addClass("state-current")});if(f.isFunction(a.onRootClick))a.onRootClick(f(this),c)});if(f.isFunction(a.onComplete))a.onComplete(e)})};this._menuBarFromXML=function(a,c){return c.foreach(function(){var c,e=x(this,"MENUITEM");if(e&&e.length){for(c=0;c<e.length;c++){var b=f(e[c]).attr("menuId"),d=f(e[c]).attr("menuTitle"),u="";a.useGubun&&c!=e.length-1&&(u+=a.useGubun);f(e[c]).attr("style");a.menuone+='<li id="'+b+'"><a id="'+
b+'">'+d+"</a>"+u+"</li>";c==e.length-1&&(a.menuone+="</ul>")}f(a.renderTo).find(":first").before(a.menuone);h||(h=new k._MenuCollection);for(c=0;c<e.length;c++)k._menuFromXMLMenuItem(a,null,h,m(e[c]))}})};this._menuFromXMLMenuItem=function(a,c,g,e){var b=function(c){var e=[],g,d,l,h,r=null;d=x(c,"MENUITEM");for(l=0;l<d.length;l++)if(c=[],g=f(d[l]),g.attr("menuTitle")){if(h=y(d[l],"MENU"))c=b(h);h=g.attr("menuTitle");a&&a.copyClassAttr&&(r=g.attr("class"));g=new k._MenuItem({src:h,addClass:r,objLi:g},
a);e.push(g);c.length&&new k._Menu(g,c,a)}else e.push(new k._MenuItem("",a));return e};return e.foreach(function(){var e;if(c||(e=y(this,"MENU")))e=c?f(c).clone(!0)[0]:e,menuItems=b(e),menuItems.length&&(a.targetId=f(this).attr("menuId"),e=new k._Menu(this,menuItems,a),h&&h.addMenu(e))})};this._loadJSON=function(a,c,g){var e=a.ulTarget;if(e)if(a.useMegaMenuType&&"4depth"==a.useMegaMenuType){var b=f("<div></div>"),d=1<a.useMegaMenuFirstHidden.split(".").length?a.useMegaMenuFirstHidden.split(".")[1]:
a.useMegaMenuFirstHidden.split(".")[0];b.addClass(d);b.appendTo("body");var h=f(a.useMegaMenuFirstVisible);h.parent().show();var n=tmpLI=tmpA=tmpTEXT=null;0!=b.get(0).childNodes.length&&(n=b.find("ul"),n.remove());n=f("<ul></ul>");n.appendTo(b);var q=null;if(0<c.length)for(var l=0;l<c.length;l++){q=c[l];if(0!=l&&a.useMegaMenuSeparator){tmpLI=f("<li></li>");var t=f("<div></div>"),d=1<a.useMegaMenuSeparator.split(".").length?a.useMegaMenuSeparator.split(".")[1]:a.useMegaMenuSeparator.split(".")[0];
t.addClass(d).appendTo(tmpLI);tmpLI.appendTo(n)}tmpLI=f("<li></li>");tmpA=f("<a></a>").attr("id",q.menuId).attr("title",q.menuTitle).attr("menuidx",l).bind("click",function(){var b=f(this),e=b.attr("menuidx"),b=b.attr("id"),d=c[e],e=g[e],k=h.find("ul > li");if(1<k.length)for(l=0;l<k.length;l++){var p=f(k[l]).find("a");p.attr("id")!=b?p.hide():p.show()}a.useMegaMenuType="";a.ulTarget=a.ulTargetOrigin+"-"+b;ncMegaMenu._loadJSON(a,d.Menu,e.Menu)}).html(q.menuTitle);tmpA.appendTo(tmpLI);tmpLI.appendTo(n);
if(0==l){if(f.isFunction(a.onAutoComplete))a.onAutoComplete(c,a);a.onAutoComplete=null;tmpA.trigger("click")}if(l==c.length-1){d=n.clone();a.useMegaMenuSeparator&&d.find(a.useMegaMenuSeparator).parent().remove();0!=h.get(0).childNodes.length&&h.find("ul").remove();d.appendTo(h);var d=null,p=h.parent();p.hover(function(){var a=f(this).offset().top,c=f(this).height(),e=f(this).offset().left;b.css({top:a+c,left:e,width:p.width()}).show()},function(){});b.hover(function(){},function(){b.hide()});b.bind("click",
function(){b.hide()});m.behavior.IApplyBlockUI&&m.behavior.IApplyBlockUI(b,!0,{callWidget:"menu",type:"content"})}tmpLI=tmpA=tmpTEXT=null}}else{n=f(a.renderTo).children();if(1<n.length)for(l=0;l<n.length;l++)d=f(n[l]),d.attr("id")!=e?d.hide():d.show();a.menuone='<ul id="'+e+'" class="menu-root">';f.each(c,function(b,e){var g=c[b].menuId,d=c[b].menuTitle,h=c[b].showTitle,l="";a.useGubun&&c.length-1!=b&&(l+=a.useGubun);a.menuone=h?a.menuone+('<li id="'+g+'"><a id="'+g+'" showTitle="'+h+'" menuTitle="'+
d+'">'+d+"</a>"+l+"</li>"):a.menuone+('<li id="'+g+'"><a id="'+g+'" menuTitle="'+d+'">'+d+"</a>"+l+"</li>");c.length-1==b&&(a.menuone+="</ul>")});f(a.renderTo).find(":first").before(a.menuone);f("ul#"+e+"> li > a").click(function(b,c){var g=f(this).attr("id");f("ul#"+e+"> li").each(function(a,c){g!=f(this).attr("id")?f("> a",this).removeClass("state-current"):f("> a",this).addClass("state-current")});if(f.isFunction(a.onRootClick))a.onRootClick(f(this),c)});a.useMegaMenu&&k._menuBarFromJSON(a,m(c));
if(f.isFunction(a.onComplete))a.onComplete(g,a);if(f.isFunction(a.onAutoComplete))a.onAutoComplete(g,a)}};this._menuBarFromJSON=function(a,c){return c.foreach(function(){var c=this.Menu;c&&c.length&&k._menuFromJSONMenuItem(a,null,h,m(this))})};this._menuFromJSONMenuItem=function(a,c,d,e){var b=function(c,e){var d=[],g,l,h,f,n,r=null;h=c.Menu;"sub"==e&&(h=c);for(f=0;f<h.length;f++)if(g=[],l=h[f],l.menuTitle){if(n=l.Menu)g=b(n,"sub");n=l.menuTitle;a&&a.copyClassAttr&&(r=l["class"]);l=new k._MenuItem({src:n,
addClass:r,objLi:l},a);d.push(l);g.length&&new k._Menu(l,g,a)}else d.push(new k._MenuItem("",a));return d};return e.foreach(function(){var e;if(c||(e=this))e=c?f(c).clone(!0)[0]:e,e=b(e,""),e.length&&(a.targetId=this.menuId,e=new k._Menu(this,e,a),h&&h.addMenu(e))})};this.createMenuScroller=function(a){this.ExcuteCreateMenuScroller||naw._require("naw.thirdparty.scrollto",function(){});this.scrollTo(a);this.ExcuteCreateMenuScroller=!0};this.scrollTo=function(a){var c=jQuery("#menuDiv:first"),d=jQuery("#menuDiv > ul > li");
if(a&&1==a.isNotApply)d.unbind("click");else{a&&0==a.isNotHandlerLI&&d.bind("click",function(){k(jQuery(this))});naw(".menu-scroller-left").click(function(){if(a&&1==a.isNotHandlerLI){if(naw(".menu-scroller-right:first").removeClass("state-disabled"),!jQuery(this).hasClass("state-disabled")){c.width();c.children("ul").width();var g=null,f=c.get(0).scrollLeft,p=0,m=!1,w=0;d.each(function(a){m||(p+=parseInt(jQuery(this).width(),10),p>f+5&&(g=0!=jQuery(this).prev().length?jQuery(this).prev():jQuery(this),
m=!0))});k(g);0==g.prev().length&&(naw(".menu-scroller-left:first").addClass("state-disabled"),naw(".menu-scroller-right:first").removeClass("state-disabled"))}}else{var w=e(),r=Math.max(0,w-b()-h());r!=w?n(r):n(-1)}});naw(".menu-scroller-right").click(function(){if(a&&1==a.isNotHandlerLI){if(naw(".menu-scroller-left:first").removeClass("state-disabled"),!jQuery(this).hasClass("state-disabled")){var g=c.width();c.children("ul").width();var k=null,p=c.get(0).scrollLeft,m=-p,r=!1,v=!1,u=!1;d.each(function(a){r&&
(k=jQuery(this),r=!1,a==d.length-1&&(v=!0));g>m&&(m+=parseInt(jQuery(this).width(),10),r=!0,0>g-m&&(k=jQuery(this),u=!0))});p=u?p+k.width()+m-g:p+k.width();v&&(p+=5,naw(".menu-scroller-right:first").addClass("state-disabled"));c.scrollTo(p,a&&a.delay?a.delay:500,{axis:"x",margin:"true"})}}else{var q=parseInt(c.get(0).scrollWidth,10)-f(),p=e(),q=Math.min(q,p+b()+h());q!=p?n(q):n(-1)}});var e=function(){return parseInt(c.get(0).scrollLeft,10)},b=function(){var a=d.length,c=f(),b=function(){var c=0;
d.each(function(a){c+=parseInt(jQuery(this).width(),10)});return Math.floor(c/a)}(),e=h();return Math.max(Math.floor(c/a-e),b)},h=function(){return parseInt(d.eq(0).css("margin-left"),10)},f=function(){return parseInt(c.get(0).clientWidth,10)},k=function(a){var c=e(),b=f(),d=h(),g=parseInt(a.position().left,10)+c;a=g+parseInt(a.width(),10);a>c+b?n(a-b+2*d):g>=c&&n(g-c)},n=function(b){__updateScrollButton=function(){var a=e(),b=parseInt(c.get(0).scrollWidth,10),d=f();naw(".menu-scroller-left:first")[0==
a?"addClass":"removeClass"]("state-disabled");naw(".menu-scroller-right:first")[a>=b-d?"addClass":"removeClass"]("state-disabled")};-1<b&&c.scrollTo(b,a&&a.delay?a.delay:500,{axis:"x",margin:"true"});__updateScrollButton()};jQuery("#menuDiv > ul").css("width",function(){h();var c=0;d.each(function(a){c+=parseInt(jQuery(this).width(),10)});c+=10;return c<f()?"":a&&1==a.isNotHandlerLI?c:(Math.round(c/14.5*10)+1)/10+"em"}());a&&0==a.isNotHandlerLI?naw(".menu-scroller-left").trigger("click"):(0==c.get(0).scrollLeft&&
naw(".menu-scroller-left:first").addClass("state-disabled"),naw(".menu-scroller-right:first").removeClass("state-disabled"))}}};var y=function(f,m){if(!f)return null;for(var k=f.firstChild;k;k=k.nextSibling)if(1==k.nodeType&&k.nodeName.toUpperCase()==m)return k;return null},x=function(f,m){if(!f)return[];for(var k=[],h=f.firstChild;h;h=h.nextSibling)1==h.nodeType&&h.nodeName.toUpperCase()==m&&(k[k.length]=h);return k},z=function(f,m,n){var h=function(a,d,e){var b="";if(a instanceof Array){"MenuItem"==
d?b+="\t>":"Menu"==d&&(b+="\t>",d="MenuItem");for(var b=b+"<Menu>",c=0,g=a.length;c<g;c++)b+=e+h(a[c],d,e+"\t")+"";b+="</Menu>"}else if("object"==typeof a){c=!1;b+=e+"<"+d;for(g in a)"@"!=g.charAt(0)&&(c=!0);if(c){for(g in a)"@"!=g.charAt(0)&&(b+=h(a[g],g,e+"\t"));b=""==b.split("</Menu>")[b.split("</Menu>").length-1]?b+("</"+d+">"):b+("></"+d+">")}}else{a="menuTitle"==d?a.toString().replace(/&/g,"＆"):a.toString();"keyTitle"==d&&(a=a.replace(/&gt;/g,"＞"),a=a.replace(/&/g,"＆"),a=a.replace(/＞/g,"&gt;"));
if(n.useToCase&&(n.useToCase.usePage&&"page"==d||n.useToCase.useMenuId&&"menuId"==d))switch(n.useToCase.htmlConf.resource){case "uppercase":a=a.toUpperCase();break;case "lowsercase":a=a.toLowerCase()}b+=e+d+" = '"+a+"'\t"}return b},d="",d="<?xml version='1.0' encoding='UTF-8'?><Menu id='menuone'>",a;for(a in f)d+=h(f[a],"MenuItem","");d+="</Menu>";return m?d.replace(/\t/g,m):d.replace(/\t|\n/g,"")},A=function(f,m,n){var h={toObj:function(d){var a={};if(1==d.nodeType){if(n&&d.attributes.length)for(var c=
0;c<d.attributes.length;c++)a["@"+d.attributes[c].nodeName]=(d.attributes[c].nodeValue||"").toString();if(d.firstChild){for(var g=c=0,e=!1,b=d.firstChild;b;b=b.nextSibling)1==b.nodeType?e=!0:3==b.nodeType&&b.nodeValue.match(/[^ \f\n\r\t\v]/)?c++:4==b.nodeType&&g++;if(e)if(2>c&&2>g)for(h.removeWhite(d),b=d.firstChild;b;b=b.nextSibling)3==b.nodeType?a["#text"]=h.escape(b.nodeValue):4==b.nodeType?a["#cdata"]=h.escape(b.nodeValue):a[b.nodeName]?a[b.nodeName]instanceof Array?a[b.nodeName][a[b.nodeName].length]=
h.toObj(b):a[b.nodeName]=[a[b.nodeName],h.toObj(b)]:a[b.nodeName]=h.toObj(b);else d.attributes.length?a["#text"]=h.escape(h.innerXml(d)):a=h.escape(h.innerXml(d));else if(c)d.attributes.length?a["#text"]=h.escape(h.innerXml(d)):a=h.escape(h.innerXml(d));else if(g)if(1<g)a=h.escape(h.innerXml(d));else for(b=d.firstChild;b;b=b.nextSibling)a["#cdata"]=h.escape(b.nodeValue)}d.attributes.length||d.firstChild||(a=null)}else 9==d.nodeType?a=h.toObj(d.documentElement):alert("unhandled node type: "+d.nodeType);
return a},toJson:function(d,a,c){var g=a?'"'+a+'"':"";if(d instanceof Array){for(var e=0,b=d.length;e<b;e++)d[e]=h.toJson(d[e],"",c+"\t");g+=(a?":[":"[")+(1<d.length?"\n"+c+"\t"+d.join(",\n"+c+"\t")+"\n"+c:d.join(""))+"]"}else if(null==d)g+=(a&&":")+"null";else if("object"==typeof d){e=[];for(b in d)e[e.length]=h.toJson(d[b],b,c+"\t");g+=(a?":{":"{")+(1<e.length?"\n"+c+"\t"+e.join(",\n"+c+"\t")+"\n"+c:e.join(""))+"}"}else g="string"==typeof d?g+((a&&":")+'"'+d.toString()+'"'):g+((a&&":")+d.toString());
return g},innerXml:function(d){var a="";if("innerHTML"in d)a=d.innerHTML;else{var c=function(a){var d="";if(1==a.nodeType){for(var d=d+("<"+a.nodeName),b=0;b<a.attributes.length;b++)d+=" "+a.attributes[b].nodeName+'="'+(a.attributes[b].nodeValue||"").toString()+'"';if(a.firstChild){d+=">";for(b=a.firstChild;b;b=b.nextSibling)d+=c(b);d+="</"+a.nodeName+">"}else d+="/>"}else 3==a.nodeType?d+=a.nodeValue:4==a.nodeType&&(d+="<![CDATA["+a.nodeValue+"]]\x3e");return d};for(d=d.firstChild;d;d=d.nextSibling)a+=
c(d)}return a},escape:function(d){return d.replace(/[\\]/g,"\\\\").replace(/[\"]/g,'\\"').replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r")},removeWhite:function(d){d.normalize();for(var a=d.firstChild;a;)if(3==a.nodeType)if(a.nodeValue.match(/[^ \f\n\r\t\v]/))a=a.nextSibling;else{var c=a.nextSibling;d.removeChild(a);a=c}else 1==a.nodeType&&h.removeWhite(a),a=a.nextSibling;return d}};9==f.nodeType&&(f=f.documentElement);f=h.toJson(h.toObj(h.removeWhite(f)),f.nodeName,"\t");return"{\n"+(m?f.replace(/\t/g,
m):f.replace(/\t|\n/g,""))+"\n}"}})(naw,jQuery);