(function(h,g){h.namespace("taskbar");var f=null;h.widget.taskbar=h.widget.Base.extend({init:function(a,c){var d=this;d.setName("taskbar");d._super();this.options=this._getOptions(this._getTemplate(a));var b=g("#"+c.id);h.subscribe("theme.change",function(b){d.changeTheme(b.themeName,b.themeBasePath)});this._create(b,this.options)},_create:function(a,c){this.buttonset=this._buttonset(a,c);this.divTaskBar=this.element;this.taskbarGroup=this.divTaskBar.find("ul");var d=this.options.taskbarView;d&&naw(d.addEvent).click(function(b){d.onCick()})},
_getOptions:function(a){var c={text:!0,label:null,icons:{reload:null,close:null},applyScrollTo:!0,scrollTo:!0,scrollDuration:0,taskbarView:null,onClick:null,onDblClick:null};return c=g.extend({},c,a)},_button:function(a,c,d){this.buttonElement=this.element=a;this.options=c;this._create=function(b,e){this.buttonElement=this.element;this.hasTitle=!!this.buttonElement.attr("title");e=this.options;e.label=this.options.label;this.buttonElement.addClass("state-current");this.buttonElement.bind("click.button",
function(){if(g.isFunction(e.onClick))e.onClick(g(this).attr("id"))});this._resetButton(d)};this._resetButton=function(b){f&&(this.options.icons=f.options.icons,this.options.onClick=f.options.onClick,this.options.onDblClick=f.options.onDblClick,this.options.label=f.options.label?f.options.label:this.options.label);var e=this.buttonElement;g("<span></span>").addClass("taskbar-title").html(this.options.label).appendTo(e).text();var a=this.options;e.children(".taskbar-title").attr("title",this.options.label).bind("dblclick",
function(b){g.isFunction(a.onDblClick)&&(b=g(this).parent().attr("id"),a.onDblClick(b))});var c=this.options.icons;if(0!=c.length)for(var d=this,k=0;k<c.length;k++){b=c[k];var h=jQuery("<span class='"+b.css+"' title='"+b.title+"' idxitem='"+k+"'></span>").bind("click",function(b){var a=c[this.getAttribute("idxitem")];a.toggleCss&&(jQuery(this).hasClass(a.css)?(jQuery(this).removeClass(a.css),jQuery(this).addClass(a.toggleCss)):(jQuery(this).removeClass(a.toggleCss),jQuery(this).addClass(a.css)));
if(jQuery.isFunction(a.onClick))a.onClick(d.element.attr("id"),b)});1==b.initHide&&h.hide();e.append(h);b=h=null}};this._create(a,c)},_buttonset:function(a,c){this.buttonElement=this.element=a;this.options=c;this.buttonElement.append("<ul></ul>");var d=this;this.options.scrollConf.apply&&naw._require("naw.thirdparty.scrollto",function(){if("next"==c.scrollConf.applyType){jQuery(":first",a);var b=c.scrollConf.duration;a.attr("scrollto",0);naw(".taskbar-scroller .prev").click(function(){if(!jQuery(this).hasClass("state-disabled")){var e=
a.attr("scrollto"),e=parseInt(e,10)-1;a.scrollTo("li:eq("+e+")",b,{axis:"x",margin:"true"});a.attr("scrollto",e);0==e?naw(".taskbar-scroller .prev").addClass("state-disabled"):naw(".taskbar-scroller .prev, .next").removeClass("state-disabled");d._resizeTab()}});naw(".next").click(function(){if(!jQuery(this).hasClass("state-disabled")){var e=jQuery("ul>li",a),c=a.attr("scrollto"),c=parseInt(c,10)+1;a.scrollTo("li:eq("+c+")",b,{axis:"x",margin:"true"});a.attr("scrollto",c);c==e.length-1?naw(".taskbar-scroller .prev").addClass("state-disabled"):
naw(".taskbar-scroller .prev, .next").removeClass("state-disabled");d._resizeTab()}});naw.subscribe("window.resize",function(b){d._resizeTab()})}});this._resizeTab=function(){var b=0,e=a.innerWidth(),c=a.get(0).scrollLeft,d=jQuery("ul>li",a);d.each(function(a){b+=jQuery(this).outerWidth(!0)});1!=d.length&&b>e?b-c<e?naw(".next").addClass("state-disabled"):naw(".taskbar-scroller .next").removeClass("state-disabled"):(0==c&&(naw(".taskbar-scroller .prev").addClass("state-disabled"),a.attr("scrollto",
0)),naw(".taskbar-scroller .next").addClass("state-disabled"))};this._create=function(b,a){f=this;this.element.addClass("taskbar-pnl")};this.add=function(b,a,c){this.options.label=a;0==this.divTaskBar.get(0).childElementCount&&this.divTaskBar.parent().removeClass("taskbarGroup-nonactive").addClass("taskbarGroup");0==this.divTaskBar.find("li#"+b).length?(this.divTaskBar.children("ul").append("<li class='taskbar-tab' id='"+b+"'></li>"),this._createActive(b,a,c)):this.active(b)};this._createActive=function(b,
e,d){this.active(b);this._create(a,c);b=this.divTaskBar.find("#"+b);new this._button(b,this.options,d)};this.insert=function(a,c,d,f){0==this.divTaskBar.get(0).childElementCount&&this.divTaskBar.parent().removeClass("taskbarGroup-nonactive").addClass("taskbarGroup");if(0==this.divTaskBar.find("li#"+c).length){var b=this.divTaskBar.children("ul").find(" > li").length;0==b||b<=a?this.divTaskBar.children("ul").append("<li class='taskbar-tab' id='"+c+"'></li>"):(a=this.divTaskBar.children("ul").find(" > li").get(a),
a=jQuery(a),a.before("<li class='taskbar-tab' id='"+c+"'></li>"));this._createActive(c,d,f)}else this.active(c)};this.remove=function(a){this.divTaskBar.find("li#"+a).remove();0!=this.taskbarGroup.length&&0==this.taskbarGroup.get(0).childNodes.length&&("undefined"!=typeof c.initDisplay&&c.initDisplay||this.element.parent().removeClass("taskbarGroup").addClass("taskbarGroup-nonactive"))};this.active=function(a,c){var b=this.divTaskBar.find("li");f=this;var d=0;b.each(function(){var b=g(this).attr("id"),
e=g(this).children().first();b!=a?(e.attr("title"),g(this).removeClass("state-current")):(c&&(e.attr("title",c),e.html(c)),b=e.attr("title"),b=naw.isEmptyTrim(b)?f.options.label:b,f.options.label=b,e.html(b),g(this).addClass("state-current"),f.options.scrollConf.apply&&f._resizeTab(d,"active"));d++})};this.changeTitle=function(a,c){this.active(a,c)}},add:function(a,c,d){this.buttonset.add(a,c,d)},insert:function(a,c,d,b){this.buttonset.insert(a,c,d,b)},remove:function(a){this.buttonset.remove(a)},
active:function(a){this.buttonset.active(a)},changeTitle:function(a,c){this.buttonset.changeTitle(a,c)}});h._addWidget("taskbar",naw.widget.taskbar)})(naw,jQuery);