DROP TABLE TB_CARGO_DEV;

-- 창고단말정보
CREATE TABLE TB_CARGO_DEV (
	  DEV_ID VARCHAR(20) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, CARGO_NM VARCHAR(100)
	, USE_YN VARCHAR(1) DEFAULT 'Y' NOT NULL
	, DEV_NM VARCHAR(50)
	, CENTER_CD VARCHAR(5)
	, AGENT_CD VARCHAR(12)
	, CH_CNT INT
	, CH1_NM VARCHAR(50)
	, CH1_MIN INT DEFAULT 0
	, CH1_MAX INT DEFAULT 4
	, CH2_NM VARCHAR(50)
	, CH2_MIN INT DEFAULT 0
	, CH2_MAX INT DEFAULT 4
	, CH3_NM VARCHAR(50)
	, CH3_MIN INT DEFAULT 0
	, CH3_MAX INT DEFAULT 4
	, CH4_NM VARCHAR(50)
	, CH4_MIN INT DEFAULT 0
	, CH4_MAX INT DEFAULT 4
	, CH5_NM VARCHAR(50)
	, CH5_MIN INT DEFAULT 0
	, CH5_MAX INT DEFAULT 4
	, CH6_NM VARCHAR(50)
	, CH6_MIN INT DEFAULT 0
	, CH6_MAX INT DEFAULT 4
	, LAST_DEV_DT DATETIME
	, LAST_SVR_DT DATETIME
	, CHARGE_ID VARCHAR(20)
	, PUSH_YN VARCHAR(1) DEFAULT 'N'
	, PUSH_IDS VARCHAR(MAX)
	, PUSH_NMS VARCHAR(MAX)
, CONSTRAINT TB_CARGO_DEV_PK PRIMARY KEY (
	DEV_ID
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '창고단말정보', 'USER', DBO, 'TABLE', TB_CARGO_DEV;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '단말ID (GW_ID(no)   대단인터페이스 : no)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', DEV_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '창고명', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CARGO_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '단말명 (대단인터페이스 : id)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', DEV_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드 (대단인터페이스 : agent_id 연동시 P로 시작되는 agent_id가 올경우 센터코드를 삽입한다)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드 (대단인터페이스 : agent_id)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널설정갯수', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널1명칭 (대단인터페이스 : dev 1 - ch1)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH1_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널1MIN', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH1_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널1MAX', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH1_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널2명칭 (대단인터페이스 : dev 1 - ch2)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH2_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널2MIN', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH2_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널2MAX', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH2_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널3명칭 (대단인터페이스 : dev 1 - ch3)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH3_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널3MIN', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH3_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널3MAX', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH3_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널4명칭 (대단인터페이스 : dev 2 - ch1)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH4_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널4MIN', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH4_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널4MAX', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH4_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널5명칭 (대단인터페이스 : dev 2 - ch2)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH5_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널5MIN', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH5_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널5MAX', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH5_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널6명칭 (대단인터페이스 : dev 2 - ch3)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH6_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널6MIN', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH6_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널6MAX', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CH6_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '최종단말연동일시', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', LAST_DEV_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '최종서버연동일시', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', LAST_SVR_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '담당자ID', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', CHARGE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '알림여부', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', PUSH_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '알림ID (PUSH대상 ID : 구분자는 ,)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', PUSH_IDS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '알림자성명 (PUSH대상 성명 : 구분자는 ,)', 'USER', DBO, 'TABLE', TB_CARGO_DEV, 'COLUMN', PUSH_NMS;

DROP TABLE TB_CARGO_HIST;

-- 창고이력
CREATE TABLE TB_CARGO_HIST (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, DEV_ID VARCHAR(20) NOT NULL
	, USE_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, TID INT NOT NULL
	, CH1 INT
	, CH2 INT
	, CH3 INT
	, CH4 INT
	, CH5 INT
	, CH6 INT
	, DEV_DT DATETIME
	, SVR_DT DATETIME
	, TEMP_VIO_CD VARCHAR(20)
	, VIO_DESC VARCHAR(200)
, CONSTRAINT TB_CARGO_HIST_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '창고이력', 'USER', DBO, 'TABLE', TB_CARGO_HIST;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '단말ID', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', DEV_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'TID (Sequence)', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', TID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널1', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', CH1;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널2', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', CH2;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널3', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', CH3;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널4', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', CH4;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널5', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', CH5;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널6', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', CH6;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '단말연동일시', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', DEV_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '서버연동일시', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', SVR_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도위반사유코드 (사용자입력; VIO_CD; 위반사유코드;)', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', TEMP_VIO_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '위반사유', 'USER', DBO, 'TABLE', TB_CARGO_HIST, 'COLUMN', VIO_DESC;


/*
DROP TABLE TB_CARGO;

-- 창고정보
CREATE TABLE TB_CARGO (
	  CARGO_ID INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, CARGO_NM VARCHAR(50)
	, USE_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, CENTER_CD VARCHAR(20)
	, OLD_CARGO_ID VARCHAR(8)
, CONSTRAINT TB_CARGO_PK PRIMARY KEY (
	CARGO_ID
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '창고정보', 'USER', DBO, 'TABLE', TB_CARGO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '창고ID (SEQ)', 'USER', DBO, 'TABLE', TB_CARGO, 'COLUMN', CARGO_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CARGO, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CARGO, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CARGO, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CARGO, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '창고명', 'USER', DBO, 'TABLE', TB_CARGO, 'COLUMN', CARGO_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_CARGO, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드', 'USER', DBO, 'TABLE', TB_CARGO, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '이전창고ID (추후삭제: 테스트 데이터 마이그용 키)', 'USER', DBO, 'TABLE', TB_CARGO, 'COLUMN', OLD_CARGO_ID;
*/

DROP TABLE TB_CAR_HIST;

-- 차량이력
CREATE TABLE TB_CAR_HIST (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, CAR_ID VARCHAR(5) NOT NULL
	, USE_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, LOG_DIV VARCHAR(1)
	, XPOS NUMERIC(20,10)
	, YPOS NUMERIC(20,10)
	, DAY_TOT_DIS INT
	, TURN_YN VARCHAR(1)
	, SPD INT
	, CH1 INT
	, CH2 INT
	, CH3 INT
	, CH4 INT
	, DEV_DT DATETIME
	, JIBUN_ADDR VARCHAR(300)
	, ROAD_ADDR VARCHAR(300)
	, TEMP_VIO_CD VARCHAR(20)
	, ARR_VIO_CD VARCHAR(20)
	, VIO_DESC VARCHAR(200)
	, TEMP_YN VARCHAR(1)
, CONSTRAINT TB_CAR_HIST_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량이력', 'USER', DBO, 'TABLE', TB_CAR_HIST;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량ID', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', CAR_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '로그구분 (M:복합, P:위치, D:온도)', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', LOG_DIV;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '위도', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', XPOS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '경도', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', YPOS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '일누적운행거리 (단위: 미터)', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', DAY_TOT_DIS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '시동여부 (Y:시동켜짐, N:시동꺼짐)', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', TURN_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '속도', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', SPD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널1', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', CH1;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널2', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', CH2;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널3', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', CH3;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널4', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', CH4;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '단말연동일시', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', DEV_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '지번주소', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', JIBUN_ADDR;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '도로명주소', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', ROAD_ADDR;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도위반사유코드 (사용자입력; VIO_CD; 위반사유코드;)', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', TEMP_VIO_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점출도착위반사유코드 (사용자입력; VIO_CD; 위반사유코드;)', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', ARR_VIO_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '위반사유', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', VIO_DESC;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도기록계작동여부', 'USER', DBO, 'TABLE', TB_CAR_HIST, 'COLUMN', TEMP_YN;

DROP TABLE TB_CAR;

-- 차량정보
CREATE TABLE TB_CAR (
	  CAR_ID VARCHAR(5) NOT NULL
	, INSERT_DT TIME DEFAULT NOW() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT TIME
	, UPDATE_ID VARCHAR(20)
	, CAR_NO VARCHAR(15)
	, CAR_TID VARCHAR(12)
	, USE_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, DTG_YN VARCHAR(1) DEFAULT ('N') NOT NULL
	, RENT_YN VARCHAR(1) DEFAULT ('N')
	, RENT_IF_STAT VARCHAR(1)
	, CENTER_CD VARCHAR(20)
	, AGENT_CD VARCHAR(12)
	, COMPANY_CD VARCHAR(20)
	, WET_CD VARCHAR(5)
	, CH_CNT INT
	, CH1_MIN INT DEFAULT 0
	, CH1_MAX INT DEFAULT 5
	, CH2_MIN INT DEFAULT 0
	, CH2_MAX INT DEFAULT 5
	, CH3_MIN INT DEFAULT 0
	, CH3_MAX INT DEFAULT 5
	, CH4_MIN INT DEFAULT 0
	, CH4_MAX INT DEFAULT 5
	, DRV_NM VARCHAR(20)
	, DRV_TEL_NO VARCHAR(12)
	, DRV_HP_NO VARCHAR(12)
	, DRV_ZIP_NO VARCHAR(6)
	, DRV_ADDR1 VARCHAR(100)
	, DRV_ADDR2 VARCHAR(100)
	, LAST_POS_DT TIME
	, LAST_TEMP_DT TIME
	, PUSH_YN VARCHAR(1) DEFAULT 'Y'
	, PUSH_IDS VARCHAR(10000)
	, PUSH_NMS VARCHAR(10000)
	, BIZ_SHOW_CD VARCHAR(1) DEFAULT 'D'
, CONSTRAINT TB_CAR_PK PRIMARY KEY (
	CAR_ID
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량정보', 'USER', DBO, 'TABLE', TB_CAR;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량ID (식별고유번호1자리+차량번호뒷4자리)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CAR_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량번호', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CAR_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량TID (3G전화번호=단말기ID)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CAR_TID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'DTG연동여부', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', DTG_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '용차여부', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', RENT_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '용차인터페이스상태 (P: 처리중, Y: 성공, N: 실패)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', RENT_IF_STAT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '소속회사코드', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', COMPANY_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차종(톤)코드 (030; 차량중량;)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', WET_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널설정갯수', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CH_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널1MIN', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CH1_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널1MAX', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CH1_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널2MIN', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CH2_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널2MAX', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CH2_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널3MIN', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CH3_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널3MAX', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CH3_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널4MIN', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CH4_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널4MAX', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', CH4_MAX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '운전자명', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', DRV_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '전화번호 (운전자전화번호)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', DRV_TEL_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '휴대폰번호 (운전자휴대폰번호)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', DRV_HP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '우편번호 (운전자우편번호)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', DRV_ZIP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '지번주소 (운전자지번주소)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', DRV_ADDR1;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '상세주소 (운전자상세주소)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', DRV_ADDR2;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '최종위치연동일시', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', LAST_POS_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '최종온도연동일시', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', LAST_TEMP_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '알림여부', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', PUSH_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '알림ID (PUSH대상 ID : 구분자는 ,)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', PUSH_IDS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '알림자성명 (PUSH대상 성명 : 구분자는 ,)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', PUSH_NMS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량업무구분표시코드 (020; 차량업무구분; D:배송, T:수송)', 'USER', DBO, 'TABLE', TB_CAR, 'COLUMN', BIZ_SHOW_CD;

DROP TABLE TB_CD;

-- 코드
CREATE TABLE TB_CD (
	  GRP_CD VARCHAR(20) NOT NULL
	, CD VARCHAR(20) NOT NULL
	, INSERT_DT TIME DEFAULT NOW() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT TIME
	, UPDATE_ID VARCHAR(20)
	, USE_YN VARCHAR(1) DEFAULT ('Y')
	, CD_NM VARCHAR(50) NOT NULL
	, APL_STR_DD VARCHAR(8)
	, APL_END_DD VARCHAR(8)
	, CD_DESC VARCHAR(500)
	, ETC1 VARCHAR(2000)
	, ETC2 VARCHAR(2000)
	, ETC3 VARCHAR(2000)
	, SEQ INT
, CONSTRAINT TB_CD_PK PRIMARY KEY (
	GRP_CD, CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '코드', 'USER', DBO, 'TABLE', TB_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '그룹코드', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', GRP_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '코드', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '코드명', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', CD_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '적용시작일', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', APL_STR_DD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '적용종료일', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', APL_END_DD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '코드설명', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', CD_DESC;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '기타1', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', ETC1;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '기타2', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', ETC2;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '기타3', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', ETC3;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '정렬순서', 'USER', DBO, 'TABLE', TB_CD, 'COLUMN', SEQ;

DROP TABLE TB_GRP_CD;

-- 그룹코드
CREATE TABLE TB_GRP_CD (
	  GRP_CD VARCHAR(20) NOT NULL
	, INSERT_DT TIME DEFAULT NOW() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT TIME
	, UPDATE_ID VARCHAR(20)
	, USE_YN VARCHAR(1) DEFAULT ('Y')
	, GRP_NM VARCHAR(50) NOT NULL
	, APL_STR_DD VARCHAR(8)
	, APL_END_DD VARCHAR(8)
	, GRP_DESC VARCHAR(500)
, CONSTRAINT TB_GRP_CD_PK PRIMARY KEY (
	GRP_CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '그룹코드', 'USER', DBO, 'TABLE', TB_GRP_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '그룹코드', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', GRP_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '그룹코드명', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', GRP_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '적용시작일', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', APL_STR_DD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '적용종료일', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', APL_END_DD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '그룹코드설명', 'USER', DBO, 'TABLE', TB_GRP_CD, 'COLUMN', GRP_DESC;

DROP TABLE TB_MSG;

-- 메시지
CREATE TABLE TB_MSG (
	  MSG_ID VARCHAR(20) NOT NULL
	, INSERT_DT TIME DEFAULT NOW() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT TIME
	, UPDATE_ID VARCHAR(20)
	, MSG_TYPE VARCHAR(1)
	, MSG_NM VARCHAR(100) NOT NULL
	, MSG_DESC VARCHAR(2000)
, CONSTRAINT TB_MSG_PK PRIMARY KEY (
	MSG_ID
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '메시지', 'USER', DBO, 'TABLE', TB_MSG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '메시지ID', 'USER', DBO, 'TABLE', TB_MSG, 'COLUMN', MSG_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_MSG, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_MSG, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_MSG, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_MSG, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '메시지유형 (MSG_TYPE; I: 정보, W: 경고, E: 업무오류, F: 시스템에러, S: 성공)', 'USER', DBO, 'TABLE', TB_MSG, 'COLUMN', MSG_TYPE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '메시지내용', 'USER', DBO, 'TABLE', TB_MSG, 'COLUMN', MSG_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '메시지상세', 'USER', DBO, 'TABLE', TB_MSG, 'COLUMN', MSG_DESC;

/*
DROP TABLE TB_USER_CENTER;

-- 사용자별소속
CREATE TABLE TB_USER_CENTER (
	  USER_ID VARCHAR(20) NOT NULL
	, CENTER_CD VARCHAR(50) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
, CONSTRAINT TB_USER_CENTER_PK PRIMARY KEY (
	USER_ID, CENTER_CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용자별소속', 'USER', DBO, 'TABLE', TB_USER_CENTER;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용자ID', 'USER', DBO, 'TABLE', TB_USER_CENTER, 'COLUMN', USER_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드 (소속)', 'USER', DBO, 'TABLE', TB_USER_CENTER, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_USER_CENTER, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_USER_CENTER, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_USER_CENTER, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_USER_CENTER, 'COLUMN', UPDATE_ID;
*/

DROP TABLE TB_USER_HIST;

-- 사용자접속이력
CREATE TABLE TB_USER_HIST (
	  SEQ INT NOT NULL
	, INSERT_DT TIME DEFAULT NOW() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT TIME
	, UPDATE_ID VARCHAR(20)
	, USER_ID VARCHAR(20) NOT NULL
	, IP_ADDR VARCHAR(15)
	, LOGIN_GB VARCHAR(1)
	, WEB_MOB_GB VARCHAR(1)
, CONSTRAINT TB_USER_HIST_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용자접속이력', 'USER', DBO, 'TABLE', TB_USER_HIST;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '일련번호 (SEQ)', 'USER', DBO, 'TABLE', TB_USER_HIST, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_USER_HIST, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_USER_HIST, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_USER_HIST, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_USER_HIST, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '로그인ID', 'USER', DBO, 'TABLE', TB_USER_HIST, 'COLUMN', USER_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '접속IP', 'USER', DBO, 'TABLE', TB_USER_HIST, 'COLUMN', IP_ADDR;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '로그인아웃구분 (1: 로그인, 2: 로그아웃)', 'USER', DBO, 'TABLE', TB_USER_HIST, 'COLUMN', LOGIN_GB;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '모바일웹구분 (M: 모바일, W: 웹)', 'USER', DBO, 'TABLE', TB_USER_HIST, 'COLUMN', WEB_MOB_GB;

DROP TABLE TB_USER;

-- 사용자정보
CREATE TABLE TB_USER (
	  USER_ID VARCHAR(20) NOT NULL
	, INSERT_DT TIME DEFAULT NOW() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT TIME
	, UPDATE_ID VARCHAR(20)
	, USE_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, USER_NM VARCHAR(50)
	, USER_PWD VARCHAR(200)
	, AUTH_CD VARCHAR(20)
	, CENTER_CD VARCHAR(10)
	, AUTH_CENTER_CD VARCHAR(500)
	, TEL_NO VARCHAR(11)
	, HP_NO VARCHAR(11)
	, FAX_NO VARCHAR(11)
	, EMAIL VARCHAR(50)
	, LAST_CON_DT TIME
	, AGENT_CD VARCHAR(12)
	, PUSH_YN VARCHAR(1)
, CONSTRAINT TB_USER_PK PRIMARY KEY (
	USER_ID
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용자정보', 'USER', DBO, 'TABLE', TB_USER;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용자ID', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', USER_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:정상, N:미사용)', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '성명', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', USER_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '패스워드 (단방향 암호화 : MD5)', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', USER_PWD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '권한코드 (AUTH; 300: 배송기사, 104: 앱관리자, 100: 최고관리자, 500: 현장관리자)', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', AUTH_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '소속센터코드 (소속 CENTER; 1400: 경산공장, 1300: 광주공장, 2700: 군포센터, 2200: 평택물류(매일)…)', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '권한센터코드 (소속 CENTER; 1400: 경산공장, 1300: 광주공장, 2700: 군포센터, 2200: 평택물류(매일)…)', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', AUTH_CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '전화번호', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', TEL_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '휴대폰번호', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', HP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '팩스번호', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', FAX_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '이메일', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', EMAIL;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '최종접속일시', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', LAST_CON_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '알림수신여부', 'USER', DBO, 'TABLE', TB_USER, 'COLUMN', PUSH_YN;

DROP TABLE TB_NOTICE;

-- 공지사항
CREATE TABLE TB_NOTICE (
	  SEQ INT NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, TITLE VARCHAR(100) NOT NULL
	, CONT VARCHAR(MAX)
	, SHOW_YN VARCHAR(1)
, CONSTRAINT TB_NOTICE_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '공지사항', 'USER', DBO, 'TABLE', TB_NOTICE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_NOTICE, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_NOTICE, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_NOTICE, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_NOTICE, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_NOTICE, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '제목', 'USER', DBO, 'TABLE', TB_NOTICE, 'COLUMN', TITLE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '본문', 'USER', DBO, 'TABLE', TB_NOTICE, 'COLUMN', CONT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '표시여부 (Y: 표시, N: 미표시)', 'USER', DBO, 'TABLE', TB_NOTICE, 'COLUMN', SHOW_YN;

DROP TABLE TB_QNA;

-- 1대1문의
CREATE TABLE TB_QNA (
	  SEQ INT NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, QUE_TITLE VARCHAR(100)
	, QUE_CONT VARCHAR(MAX)
	, QUE_ID VARCHAR(20)
	, QUE_MOD_DT DATETIME
	, ANS_TITLE VARCHAR(100)
	, ANS_CONT VARCHAR(MAX)
	, ANS_ID VARCHAR(20)
	, ANS_MOD_DT DATETIME
	, ANS_YN VARCHAR(1)
	, SHOW_YN VARCHAR(1)
, CONSTRAINT TB_QNA_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '1대1문의', 'USER', DBO, 'TABLE', TB_QNA;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '질문제목', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', QUE_TITLE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '질문본문', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', QUE_CONT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '질문자ID', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', QUE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '질문작성일시', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', QUE_MOD_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '답변제목', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', ANS_TITLE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '답변본문', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', ANS_CONT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '답변자ID', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', ANS_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '답변작성일시', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', ANS_MOD_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '답변여부 (Y: 답변완료, N: 답변대기)', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', ANS_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '표시여부 (Y: 표시, N: 미표시)', 'USER', DBO, 'TABLE', TB_QNA, 'COLUMN', SHOW_YN;

DROP TABLE TB_FILE;

-- 첨부파일
CREATE TABLE TB_FILE (
	  FILE_SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, FILE_NM VARCHAR(300) NOT NULL
	, FILE_EXT VARCHAR(40)
	, FILE_TYPE VARCHAR(80)
	, FILE_SIZE INT
	, FILE_KIND VARCHAR(1)
	, FILE_DIV VARCHAR(10)
	, FILE_KEY VARCHAR(100)
	, SAVE_FILE_NM VARCHAR(300)
	, SAVE_FILE_PATH VARCHAR(300)
	, DEL_YN VARCHAR(1)
	, TEMP_YN VARCHAR(1) DEFAULT 'Y'
, CONSTRAINT TB_FILE_PK PRIMARY KEY (
	FILE_SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '첨부파일', 'USER', DBO, 'TABLE', TB_FILE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', FILE_SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일명 (원본파일명)', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', FILE_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일확장자', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', FILE_EXT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일형식 (컨텐츠타입)', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', FILE_TYPE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일크기 (byte)', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', FILE_SIZE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일종류 (I: 이미지, F: 첨부파일, R: RAW데이터)', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', FILE_KIND;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일구분 (FILE_DIV; NOTICE: 공지사항, QNA: 1:1문의)', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', FILE_DIV;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일KEY (게시물번호나 FK용 KEY)', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', FILE_KEY;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '저장파일명', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', SAVE_FILE_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '저장경로', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', SAVE_FILE_PATH;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '삭제여부 (Y:삭제, N:정상)', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', DEL_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '임시여부 (Y:임시, N:정상)', 'USER', DBO, 'TABLE', TB_FILE, 'COLUMN', TEMP_YN;

DROP TABLE TB_SEQ;

-- 일련번호
CREATE TABLE TB_SEQ (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, TABLE_NM VARCHAR(50)
	, COLUMN_NM VARCHAR(50) DEFAULT 'SEQ'
	, PREFIX VARCHAR(20)
	, NOW_SEQ INT
, CONSTRAINT TB_SEQ_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '일련번호', 'USER', DBO, 'TABLE', TB_SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_SEQ, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_SEQ, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_SEQ, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_SEQ, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_SEQ, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '테이블명', 'USER', DBO, 'TABLE', TB_SEQ, 'COLUMN', TABLE_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '컬럼명', 'USER', DBO, 'TABLE', TB_SEQ, 'COLUMN', COLUMN_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '접두어', 'USER', DBO, 'TABLE', TB_SEQ, 'COLUMN', PREFIX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '현재순번', 'USER', DBO, 'TABLE', TB_SEQ, 'COLUMN', NOW_SEQ;

DROP TABLE TB_CAR_EVENT;

-- 차량DTG이벤트(일별)
CREATE TABLE TB_CAR_EVENT (
	  STD_DATE DATE NOT NULL
	, CAR_ID VARCHAR(5) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, CENTER_CD VARCHAR(5)
	, AGENT_CD VARCHAR(12)
	, DRV_CNT INT
	, DRV_DIS INT
	, DRV_SEC INT
	, DRV_MIN INT
	, OVER_SPD_CNT INT
	, BURST_SPD_CNT INT
	, DROP_SPD_CNT INT
	, IDLE_CNT INT
, CONSTRAINT TB_CAR_EVENT_PK PRIMARY KEY (
	STD_DATE, CAR_ID
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량DTG이벤트(일별)', 'USER', DBO, 'TABLE', TB_CAR_EVENT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '기준일자 (YYYYMMDD)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', STD_DATE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량ID', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', CAR_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드 (센터일경우는 센터코드만 삽입)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드 (대리점일경우는 대리점코드만 삽입)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '실운행횟수 (TB_CAR_STAT에서 수배송 합계의 횟수)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', DRV_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '실운행거리 (TB_CAR_STAT에서 수배송 합계의 횟수; 단위 : Km)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', DRV_DIS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '실운행시각 (TB_CAR_STAT에서 수배송 합계의 횟수; 단위 : 초)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', DRV_SEC;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '운행시간 (S1에서 넘어온 데이터; 단위:분)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', DRV_MIN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '과속횟수 (S1에서 넘어온 데이터)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', OVER_SPD_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '급가속횟수 (S1에서 넘어온 데이터)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', BURST_SPD_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '급감속횟수 (S1에서 넘어온 데이터)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', DROP_SPD_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '공회전횟수 (S1에서 넘어온 데이터)', 'USER', DBO, 'TABLE', TB_CAR_EVENT, 'COLUMN', IDLE_CNT;

DROP TABLE TB_CENTER;

-- 센터정보
CREATE TABLE TB_CENTER (
	  CENTER_CD VARCHAR(5) NOT NULL
	, INSERT_DT TIME DEFAULT NOW() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT TIME
	, UPDATE_ID VARCHAR(20)
	, CENTER_NM VARCHAR(50)
	, USE_YN VARCHAR(1)
	, ZIP_CD VARCHAR(6)
	, SI VARCHAR(20)
	, GU VARCHAR(20)
	, DONG VARCHAR(20)
	, RI VARCHAR(50)
	, S_BUNJI VARCHAR(20)
	, E_BUNJI VARCHAR(20)
	, STAFF_NM VARCHAR(20)
	, STAFF_HP_NO VARCHAR(12)
	, STAFF_TEL_NO VARCHAR(12)
	, CVO_ZIP VARCHAR(6)
	, CVO_SI VARCHAR(50)
	, CVO_ADDR VARCHAR(300)
	, XPOS NUMERIC(20,10)
	, YPOS NUMERIC(20,10)
, CONSTRAINT TB_CENTER_PK PRIMARY KEY (
	CENTER_CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터정보', 'USER', DBO, 'TABLE', TB_CENTER;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드 (소속)', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터명', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', CENTER_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '우편번호', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', ZIP_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '시', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', SI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '구', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', GU;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '동', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', DONG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '리', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', RI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '시작번지', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', S_BUNJI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '종료번지', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', E_BUNJI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '관리자명', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', STAFF_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '관리자휴대폰', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', STAFF_HP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '관리자전화번호', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', STAFF_TEL_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CVO우편번호', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', CVO_ZIP;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CVO시도', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', CVO_SI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CVO주소', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', CVO_ADDR;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '위도', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', XPOS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '경도', 'USER', DBO, 'TABLE', TB_CENTER, 'COLUMN', YPOS;

DROP TABLE TB_AGENT;

-- 대리점정보
CREATE TABLE TB_AGENT (
	  AGENT_CD VARCHAR(12) NOT NULL
	, INSERT_DT TIME DEFAULT NOW() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT TIME
	, UPDATE_ID VARCHAR(20)
	, AGENT_NM VARCHAR(50)
	, USE_YN VARCHAR(1)
	, CENTER_CD VARCHAR(5) NOT NULL
	, EMP_NO VARCHAR(7)
	, SI VARCHAR(300)
	, GU VARCHAR(20)
	, DONG VARCHAR(20)
	, RI VARCHAR(50)
	, S_BUNJI VARCHAR(20)
	, E_BUNJI VARCHAR(20)
	, STAFF_NM VARCHAR(20)
	, STAFF_HP_NO VARCHAR(11)
	, STAFF_TEL_NO VARCHAR(11)
	, SAP_UPDATE_DT TIME
	, CVO_ZIP VARCHAR(6)
	, CVO_SI VARCHAR(50)
	, CVO_ADDR VARCHAR(300)
	, XPOS NUMERIC(20,10)
	, YPOS NUMERIC(20,10)
	, CVO_HP_NO VARCHAR(11)
	, CVO_TEL_NO VARCHAR(11)
	, SO_CD VARCHAR(4)
	, CH_CD VARCHAR(3)
	, NORMAL_FROM VARCHAR(4)
	, NORMAL_TO VARCHAR(4)
	, WEEKEND_FROM VARCHAR(4)
	, WEEKEND_TO VARCHAR(4)
, CONSTRAINT TB_AGENT_PK PRIMARY KEY (
	AGENT_CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점정보', 'USER', DBO, 'TABLE', TB_AGENT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점명 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', AGENT_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (사용여부 Y인것만 노출)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '담당사원사번 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', EMP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '시 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', SI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '구 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', GU;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '동 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', DONG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '리 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', RI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '시작번지 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', S_BUNJI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '종료번지 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', E_BUNJI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점장명 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', STAFF_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점장휴대폰 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', STAFF_HP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점장전화번호 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', STAFF_TEL_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'SAP수정일시 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', SAP_UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CVO우편번호 (CVO에서 편집가능)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', CVO_ZIP;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CVO시도 (CVO에서 편집가능)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', CVO_SI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CVO주소 (CVO에서 편집가능)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', CVO_ADDR;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '위도 (CVO에서 편집가능)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', XPOS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '경도 (CVO에서 편집가능)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', YPOS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CVO휴대폰 (CVO에서 편집가능)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', CVO_HP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CVO전화번호 (CVO에서 편집가능)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', CVO_TEL_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사업장코드 (SO_CD; 1001, 1002…)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', SO_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '영업그룹코드 (CH_CD; 112, 121, 122…)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', CH_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '평일출발시각 (CVO에서 편집가능 : HHMI)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', NORMAL_FROM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '평일도착시각 (CVO에서 편집가능 : HHMI)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', NORMAL_TO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '주말출발시각 (CVO에서 편집가능 : HHMI)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', WEEKEND_FROM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '주말도착시각 (CVO에서 편집가능 : HHMI)', 'USER', DBO, 'TABLE', TB_AGENT, 'COLUMN', WEEKEND_TO;

DROP TABLE TB_DELI;

-- 납품정보
CREATE TABLE TB_DELI (
	  SHIP_NO VARCHAR(10) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, SHIP_REQ_DATE DATE NOT NULL
	, CENTER_CD VARCHAR(5) NOT NULL
	, CENTER_NM VARCHAR(50)
	, CAR_ID VARCHAR(5) NOT NULL
	, CENTER_RDY_DT DATETIME
	, RELEASE_YN VARCHAR(1) DEFAULT 'N'
	, DELI_YN VARCHAR(1) DEFAULT 'N'
	, UNLOAD_CHK_YN VARCHAR(1) DEFAULT 'N'
	, DELIY_DT DATETIME
	, DELIY_DIV VARCHAR(1)
, CONSTRAINT TB_DELI_PK PRIMARY KEY (
	SHIP_NO
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품정보', 'USER', DBO, 'TABLE', TB_DELI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '선적번호', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', SHIP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품요청일', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', SHIP_REQ_DATE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터명', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', CENTER_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량ID', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', CAR_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터출발대기일시', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', CENTER_RDY_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '현장출고완료여부', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', RELEASE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '배송완료여부', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', DELI_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '하차검수완료여부', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', UNLOAD_CHK_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '배송완료일시', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', DELIY_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '배송완료구분 (1. 정상마감, 2. 운전자마감, 3. 배치마감)', 'USER', DBO, 'TABLE', TB_DELI, 'COLUMN', DELIY_DIV;

DROP TABLE TB_DELI_DTL;

-- 납품정보상세
CREATE TABLE TB_DELI_DTL (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, SHIP_NO VARCHAR(10) NOT NULL
	, AGENT_CD VARCHAR(12) NOT NULL
	, DELI_NO VARCHAR(10) NOT NULL
	, AGENT_NM VARCHAR(50)
	, ARR_EXPECT_DT DATETIME
	, ARR_DT DATETIME
	, ARR_GAP_SEC INT
	, DELAY_YN VARCHAR(1) DEFAULT 'N'
	, AGENT_OK_YN VARCHAR(1) DEFAULT 'N'
	, AGENT_STR_DT DATETIME
	, TOT_SRV_SEC INT
	, OUT_CNT_IF_STAT VARCHAR(1)
	, IN_CNT_IF_STAT VARCHAR(1)
	, RCPT_YN VARCHAR(1) DEFAULT 'N'
	, AGENT_GAP_SEC INT
	, AGENT_DELAY_YN VARCHAR(1) DEFAULT 'N'
	, BIZ_CD VARCHAR(1)
	, SAP_BIZ_CD VARCHAR(4)
	, IO_SAVE_RDY_YN VARCHAR(1) DEFAULT 'N'
	, IO_SAVE_YN VARCHAR(1) DEFAULT 'N'
	, IO_SAVE_FIRST_DT DATETIME
, CONSTRAINT TB_DELI_DTL_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품정보상세', 'USER', DBO, 'TABLE', TB_DELI_DTL;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '선적번호', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', SHIP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품번호', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', DELI_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점명', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', AGENT_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '도착예정일시', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', ARR_EXPECT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '도착일시', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', ARR_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '도착오차시간 (단위: 초)', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', ARR_GAP_SEC;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '지연여부', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', DELAY_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점승인여부', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', AGENT_OK_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점출발일시', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', AGENT_STR_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '총운행시간 (단위: 초)', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', TOT_SRV_SEC;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '출고수량전송상태 (R: 전송대기, Y: 성공, N: 실패)', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', OUT_CNT_IF_STAT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '회수수량전송상태 (R: 전송대기, Y: 성공, N: 실패)', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', IN_CNT_IF_STAT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '전표확인여부', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', RCPT_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점기준오차시간 (출도착시간은 From To 형태로 되어 있는데 해당 시간을 벗어나면 from 보다 작거나 To 보다 크면 해당 차이시간을 초단위로 표현을 한다.)', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', AGENT_GAP_SEC;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점기준지연여부', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', AGENT_DELAY_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량업무구분코드 (020; 차량업무구분; D:배송, T:수송)', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', BIZ_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'SAP업무구분코드 (SAP 데이터 그대로 저장; D: Z001 T: Z002,Z003,Z004)', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', SAP_BIZ_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '출고회수수량저장준비여부', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', IO_SAVE_RDY_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '출고회수수량저장여부', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', IO_SAVE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '출고회수수량처음저장일시', 'USER', DBO, 'TABLE', TB_DELI_DTL, 'COLUMN', IO_SAVE_FIRST_DT;

DROP TABLE TB_SAP_IF_HIST;

-- SAP 인터페이스 이력
CREATE TABLE TB_SAP_IF_HIST (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, IF_SEQ VARCHAR(10) NOT NULL
	, SEND_DIV VARCHAR(1) NOT NULL
	, CENTER_CD VARCHAR(4)
	, SHIP_NO VARCHAR(10)
	, DELI_NO VARCHAR(10)
	, IF_DIV_CD VARCHAR(2)
	, SUCC_YN VARCHAR(1)
	, ERR_MSG VARCHAR(MAX)
, CONSTRAINT TB_SAP_IF_HIST_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'SAP 인터페이스 이력', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시 (인테페이스일시)', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '인터페이스순번', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', IF_SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '송수신구분 (U: 업로드, D: 다운로드)', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', SEND_DIV;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '선적번호', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', SHIP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품번호', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', DELI_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '인터페이스구분코드', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', IF_DIV_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '전송성공여부', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', SUCC_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '전송에러메시지', 'USER', DBO, 'TABLE', TB_SAP_IF_HIST, 'COLUMN', ERR_MSG;

DROP TABLE TB_PKG;

-- 포장재별출고회수
CREATE TABLE TB_PKG (
	  SHIP_NO VARCHAR(10) NOT NULL
	, PKG_CD VARCHAR(15) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, OUT_CNT INT DEFAULT 0
	, IN_CNT INT DEFAULT 0
	, INOUT_DIF_YN VARCHAR(1) DEFAULT 'N'
	, UPDATE_YN	VARCHAR(1) DEFAULT 'N'
	, OUT_ID VARCHAR(20)
	, IN_ID VARCHAR(20)
, CONSTRAINT TB_PKG_PK PRIMARY KEY (
	SHIP_NO, PKG_CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '포장재별출고회수', 'USER', DBO, 'TABLE', TB_PKG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '선적번호', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', SHIP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '포장재항목코드', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', PKG_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '출고수량 (센터)', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', OUT_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '회수수량 (센터)', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', IN_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '출고회수차이여부', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', INOUT_DIF_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '관리자수정여부', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', UPDATE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '출고수량입력ID (센터)', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', OUT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '회수수량입력ID (센터)', 'USER', DBO, 'TABLE', TB_PKG, 'COLUMN', IN_ID;

DROP TABLE TB_PKG_AGENT;

-- 대리점별출고회수
CREATE TABLE TB_PKG_AGENT (
	  SHIP_NO VARCHAR(10) NOT NULL
	, PKG_CD VARCHAR(15) NOT NULL
	, AGENT_CD VARCHAR(12) NOT NULL
	, DELI_NO VARCHAR(10) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, SAP_OUT_CNT INT DEFAULT 0
	, OUT_CNT INT
	, OUT_ADJ_CNT INT
	, IN_CNT INT
	, IN_ADJ_CNT INT
	, ADJ_DESC VARCHAR(160)
, CONSTRAINT TB_PKG_AGENT_PK PRIMARY KEY (
	SHIP_NO, PKG_CD, AGENT_CD, DELI_NO
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점별출고회수', 'USER', DBO, 'TABLE', TB_PKG_AGENT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '선적번호', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', SHIP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '포장재항목코드', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', PKG_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품번호', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', DELI_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'SAP출고수량 (전산출고수량)', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', SAP_OUT_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '출고수량', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', OUT_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '출고수량조정', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', OUT_ADJ_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '회수수량', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', IN_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '회수수량조정', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', IN_ADJ_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '조정사유', 'USER', DBO, 'TABLE', TB_PKG_AGENT, 'COLUMN', ADJ_DESC;

DROP TABLE TB_PKG_ANAL;

-- 포장재출고회수통계
CREATE TABLE TB_PKG_ANAL (
	  STD_YM VARCHAR(6) NOT NULL
	, CAR_ID VARCHAR(5) NOT NULL
	, PKG_CD VARCHAR(15) NOT NULL
	, AGENT_CD VARCHAR(12) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, CENTER_CD VARCHAR(5) NOT NULL
	, SAP_OUT_CNT INT DEFAULT 0
	, IN_CNT INT DEFAULT 0
	, IN_ADJ_CNT INT DEFAULT 0
	, IN_RT NUMERIC(20,10)
, CONSTRAINT TB_PKG_ANAL_PK PRIMARY KEY (
	STD_YM, CAR_ID, PKG_CD, AGENT_CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '포장재출고회수통계', 'USER', DBO, 'TABLE', TB_PKG_ANAL;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '기준년월', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', STD_YM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량ID', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', CAR_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '포장재항목코드', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', PKG_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'SAP출고수량 (전산출고수량)', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', SAP_OUT_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '회수수량', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', IN_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '회수조정수량', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', IN_ADJ_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '회수율', 'USER', DBO, 'TABLE', TB_PKG_ANAL, 'COLUMN', IN_RT;

DROP TABLE TB_ERR_LOG;

-- 에러로그
CREATE TABLE TB_ERR_LOG (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, TR_ID VARCHAR(50)
	, OBJ_NM VARCHAR(50)
	, ERR_NUM INT
	, ERR_DESC VARCHAR(2000)
, CONSTRAINT TB_ERR_LOG_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '에러로그', 'USER', DBO, 'TABLE', TB_ERR_LOG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_ERR_LOG, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_ERR_LOG, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_ERR_LOG, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_ERR_LOG, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_ERR_LOG, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '트렌젝션ID (연동시 고유ID)', 'USER', DBO, 'TABLE', TB_ERR_LOG, 'COLUMN', TR_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '오브젝트명', 'USER', DBO, 'TABLE', TB_ERR_LOG, 'COLUMN', OBJ_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '에러번호', 'USER', DBO, 'TABLE', TB_ERR_LOG, 'COLUMN', ERR_NUM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '에러상세', 'USER', DBO, 'TABLE', TB_ERR_LOG, 'COLUMN', ERR_DESC;

DROP TABLE TB_CAR_STAT;

-- 차량통계(일별)
CREATE TABLE TB_CAR_STAT (
	  STD_DATE DATE NOT NULL
	, CAR_ID VARCHAR(5) NOT NULL
	, BIZ_CD VARCHAR(1) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, CENTER_CD VARCHAR(5)
	, AGENT_CD VARCHAR(12)
	, REST_CD VARCHAR(1) DEFAULT 'N'
	, WEEKEND_YN VARCHAR(1)
	, TEMP_TOT_CNT INT
	, TEMP_NOR_CNT INT
	, TEMP_VIO_LONG_CNT INT
	, TEMP_VIO_CNT INT
	, TEMP_NOR_RT NUMERIC(20,10)
	, TEMP_HACCP_NOR_CNT INT
	, TEMP_HACCP_VIO_LONG_CNT INT
	, TEMP_HACCP_VIO_CNT INT
	, TEMP_HACCP_NOR_RT NUMERIC(20,10)
	, ARR_TOT_CNT INT
	, ARR_NOR_CNT INT
	, ARR_VIO_CNT INT
	, ARR_NOR_RT NUMERIC(20,10)
	, ARR_AGENT_NOR_CNT INT
	, ARR_AGENT_VIO_CNT INT
	, ARR_AGENT_NOR_RT NUMERIC(20,10)
	, SHIP_CNT INT
	, DELI_PLAN_CNT INT
	, DELI_COMP_CNT INT
	, DELI_NOR_CNT INT
	, DELI_VIO_CNT INT
	, DELI_COMP_SHOW VARCHAR(10)
	, DRV_CNT INT
	, DRV_DIS INT
	, DRV_SEC INT
	, LAST_AGENT_STR_DT DATETIME
	, INPUT_TEMP_VIO_CNT INT
	, INPUT_ARR_VIO_CNT INT
	, TOT_DIS INT
	, TOT_SEC INT
, CONSTRAINT TB_CAR_STAT_PK PRIMARY KEY (
	STD_DATE, CAR_ID, BIZ_CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량통계(일별)', 'USER', DBO, 'TABLE', TB_CAR_STAT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '기준일자 (YYYYMMDD)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', STD_DATE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량ID', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', CAR_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량업무구분코드 (020; 차량업무구분; D:배송, T:수송)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', BIZ_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드 (센터일경우는 센터코드만 삽입)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드 (대리점일경우는 대리점코드만 삽입)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량휴무관리코드 (1:휴차, 2:단말기고장, 3:차량수리, 4:기타, N:정상운행)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', REST_CD
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '주말여부 (Y: 주말, N: 평일)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', WEEKEND_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도전체건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TEMP_TOT_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도정상건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TEMP_NOR_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도위반건수 (TEMP_VIO_CNT->TEMP_VIO_LONG_CNT)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TEMP_VIO_LONG_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도이상건수 (TEMP_ONCE_VIO_CNT->TEMP_VIO_CNT)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TEMP_VIO_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도준수율', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TEMP_NOR_RT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '정상HACCP건수 (TEMP_HACCP_CNT -> TEMP_HACCP_NOR_CNT 변경)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TEMP_HACCP_NOR_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'HACCP온도위반건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TEMP_HACCP_VIO_LONG_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '이상HACCP건수 (추가)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TEMP_HACCP_VIO_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '정상HACCP준수율 (TEMP_HACCP_RT -> TEMP_HACCP_NOR_RT 변경)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TEMP_HACCP_NOR_RT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '전체도착건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', ARR_TOT_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '도착정상건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', ARR_NOR_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '도착위반건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', ARR_VIO_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '도착준수율', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', ARR_NOR_RT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점기준도착정상건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', ARR_AGENT_NOR_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점기준도착위반건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', ARR_AGENT_VIO_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점기준도착준수율', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', ARR_AGENT_NOR_RT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '선적건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', SHIP_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품계획건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', DELI_PLAN_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품완료건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', DELI_COMP_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품정상건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', DELI_NOR_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품위반건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', DELI_VIO_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품완료율표시 (납품완료건수 / 납품계획건수 표시)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', DELI_COMP_SHOW;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '실운행횟수 (계산로직이 성립되었을때 다시 논의;)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', DRV_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '실운행거리 (계산로직이 성립되었을때 다시 논의; 단위 : Km)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', DRV_DIS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '실운행시간 (계산로직이 성립되었을때 다시 논의; 단위: 초)', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', DRV_SEC;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '최종대리점출발일시', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', LAST_AGENT_STR_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도위반사유코드건수', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', INPUT_TEMP_VIO_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점출도착위반사유코드', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', INPUT_ARR_VIO_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '총운행거리', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TOT_DIS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '총운행시간', 'USER', DBO, 'TABLE', TB_CAR_STAT, 'COLUMN', TOT_SEC;

DROP TABLE TB_CARGO_STAT;

-- 창고통계(일별)
CREATE TABLE TB_CARGO_STAT (
	  STD_DATE DATE NOT NULL
	, DEV_ID VARCHAR(20) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, CENTER_CD VARCHAR(5)
	, AGENT_CD VARCHAR(12)
	, WEEKEND_YN VARCHAR(1)
	, TOT_CNT INT
	, NOR_CNT INT
	, VIO_LONG_CNT INT
	, VIO_CNT INT
	, NOR_RT NUMERIC(20,10)
	, INPUT_VIO_CNT INT
, CONSTRAINT TB_CARGO_STAT_PK PRIMARY KEY (
	STD_DATE, DEV_ID
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '창고통계(일별)', 'USER', DBO, 'TABLE', TB_CARGO_STAT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '기준일자', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', STD_DATE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '단말ID', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', DEV_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '주말여부 (Y: 주말, N: 평일)', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', WEEKEND_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '전체건수 (창고온도에 관련된 횟수)', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', TOT_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '정상건수', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', NOR_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '위반건수 (정해진시간동안 온도의 일시위반이 계속될 경우의 건수)', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', VIO_LONG_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '이상건수 (온도의 일시위반건수)', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', VIO_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '준수율', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', NOR_RT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도위반사유코드건수', 'USER', DBO, 'TABLE', TB_CARGO_STAT, 'COLUMN', INPUT_VIO_CNT;

DROP TABLE TB_AUTH;

-- 권한정보
CREATE TABLE TB_AUTH (
	  AUTH_CD VARCHAR(3) NOT NULL
	, MENU_CD VARCHAR(20) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, USE_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, SELECT_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, INSERT_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, UPDATE_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, DELETE_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, EXCEL_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
, CONSTRAINT TB_AUTH_PK PRIMARY KEY (
	AUTH_CD, MENU_CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '권한정보', 'USER', DBO, 'TABLE', TB_AUTH;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '권한코드 (AUTH_CD; 100: 최고관리자, 200: 웹관리자, 300: 배송기사, 500: 현장관리자, 600: 대리점담당자)', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', AUTH_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '메뉴코드', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', MENU_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '조회여부 (Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', SELECT_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록여부 (Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', INSERT_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정여부 (Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', UPDATE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '삭제여부 (Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', DELETE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '엑셀다운로드여부 (Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_AUTH, 'COLUMN', EXCEL_YN;

DROP TABLE TB_CAR_REST;

-- 차량휴무일
CREATE TABLE TB_CAR_REST (
	  CAR_ID VARCHAR(5) NOT NULL
	, STD_YM VARCHAR(6) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, REST_CNT INT DEFAULT 0 NOT NULL
	, DAY1 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY2 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY3 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY4 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY5 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY6 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY7 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY8 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY9 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY10 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY11 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY12 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY13 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY14 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY15 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY16 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY17 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY18 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY19 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY20 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY21 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY22 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY23 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY24 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY25 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY26 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY27 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY28 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY29 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY30 VARCHAR(1) DEFAULT ('N') NOT NULL
	, DAY31 VARCHAR(1) DEFAULT ('N') NOT NULL
, CONSTRAINT TB_CAR_REST_PK PRIMARY KEY (
	CAR_ID, STD_YM
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량휴무일', 'USER', DBO, 'TABLE', TB_CAR_REST;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량ID (식별고유번호1자리+차량번호뒷4자리)', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', CAR_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '기준년월 (YYYYMM)', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', STD_YM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '휴무일수', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', REST_CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '1일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY1;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '2일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY2;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '3일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY3;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '4일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY4;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '5일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY5;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '6일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY6;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '7일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY7;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '8일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY8;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '9일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY9;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '10일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY10;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '11일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY11;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '12일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY12;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '13일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY13;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '14일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY14;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '15일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY15;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '16일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY16;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '17일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY17;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '18일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY18;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '19일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY19;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '20일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY20;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '21일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY21;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '22일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY22;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '23일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY23;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '24일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY24;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '25일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY25;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '26일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY26;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '27일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY27;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '28일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY28;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '29일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY29;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '30일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY30;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '31일', 'USER', DBO, 'TABLE', TB_CAR_REST, 'COLUMN', DAY31;

DROP TABLE TB_AGENT_IO_LOG;

-- 대리점출도착 일괄처리로그
CREATE TABLE TB_AGENT_IO_LOG (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, WORK_ID VARCHAR(20) NOT NULL
	, WORK_DIV VARCHAR(1)
, CONSTRAINT TB_AGENT_IO_LOG_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점출도착일괄처리로그', 'USER', DBO, 'TABLE', TB_AGENT_IO_LOG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_AGENT_IO_LOG, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_AGENT_IO_LOG, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_AGENT_IO_LOG, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_AGENT_IO_LOG, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_AGENT_IO_LOG, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '작업자ID', 'USER', DBO, 'TABLE', TB_AGENT_IO_LOG, 'COLUMN', WORK_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '업무구분 (D: 다운로드, U: 업로드)', 'USER', DBO, 'TABLE', TB_AGENT_IO_LOG, 'COLUMN', WORK_DIV;

DROP TABLE TB_CAR_REST_LOG;

-- 차량휴무 일괄처리로그
CREATE TABLE TB_CAR_REST_LOG (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, STD_YM VARCHAR(6) NOT NULL
	, WORK_ID VARCHAR(20) NOT NULL
	, WORK_DIV VARCHAR(1)
, CONSTRAINT TB_CAR_REST_LOG_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량휴무일괄처리로그', 'USER', DBO, 'TABLE', TB_CAR_REST_LOG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_CAR_REST_LOG, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CAR_REST_LOG, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CAR_REST_LOG, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CAR_REST_LOG, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CAR_REST_LOG, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '기준년월 (YYYYMM)', 'USER', DBO, 'TABLE', TB_CAR_REST_LOG, 'COLUMN', STD_YM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '작업자ID', 'USER', DBO, 'TABLE', TB_CAR_REST_LOG, 'COLUMN', WORK_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '업무구분 (D: 다운로드, U: 업로드)', 'USER', DBO, 'TABLE', TB_CAR_REST_LOG, 'COLUMN', WORK_DIV;

DROP TABLE TB_PUSH_HIST;

-- 알림전송이력
CREATE TABLE TB_PUSH_HIST (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, SEND_ID VARCHAR(20) NOT NULL
	, SEND_TITLE VARCHAR(200) NOT NULL
	, SEND_TXT VARCHAR(4000) NOT NULL
	, RECV_ID VARCHAR(20) NOT NULL
	, PUSH_TYPE VARCHAR(2)
	, SEND_DT DATETIME
	, SEND_FLAG VARCHAR(5)
	, MSG_IDX VARCHAR(20)
	, RECV_FLAG VARCHAR(5)
	, RECV_TXT VARCHAR(200)
	, SEND_NO INT
, CONSTRAINT TB_PUSH_HIST_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '알림전송이력', 'USER', DBO, 'TABLE', TB_PUSH_HIST;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '발송자ID', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', SEND_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '발송제목', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', SEND_TITLE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '발송내용', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', SEND_TXT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수신자ID', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', RECV_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '알림종류 (01:공장출발, 02:차량온도이탈, 03:창고온도이탈, 04: 기타전송)', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', PUSH_TYPE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '발송일시', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', SEND_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '발송결과 (200:성공, 기타:실패)', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', SEND_FLAG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '메세지번호 (PUSH 서버에서 리턴받은 TID)', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', MSG_IDX;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수신결과 (200:정상처리, 기타:실패)', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', RECV_FLAG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수신결과내용', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', RECV_TXT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '발송번호 (발송인원 숫자에 관계없이 발송 1회에 대한 일련번호)', 'USER', DBO, 'TABLE', TB_PUSH_HIST, 'COLUMN', SEND_NO;

DROP TABLE TB_CAR_NOREG_HIST;

-- 미등록차량이력
CREATE TABLE TB_CAR_NOREG_HIST (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, CAR_NO VARCHAR(15) NOT NULL
	, CAR_TID VARCHAR(12) NOT NULL
	, USE_YN VARCHAR(1) DEFAULT ('Y') NOT NULL
	, LOG_DIV VARCHAR(1)
	, XPOS NUMERIC(20,10)
	, YPOS NUMERIC(20,10)
	, DAY_TOT_DIS INT
	, TURN_YN VARCHAR(1)
	, SPD INT
	, CH1 INT
	, CH2 INT
	, CH3 INT
	, CH4 INT
	, DEV_DT DATETIME
	, JIBUN_ADDR VARCHAR(300)
	, ROAD_ADDR VARCHAR(300)
	, TEMP_YN VARCHAR(1)
, CONSTRAINT TB_CAR_NOREG_HIST_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량이력', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량번호', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', CAR_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량TID (3G전화번호=단말기ID)', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', CAR_TID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (*Y:사용, N:미사용)', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '로그구분 (M:복합, P:위치, D:온도)', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', LOG_DIV;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '위도', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', XPOS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '경도', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', YPOS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '일누적운행거리 (단위: 미터)', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', DAY_TOT_DIS;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '시동여부 (Y:시동켜짐, N:시동꺼짐)', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', TURN_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '속도', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', SPD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널1', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', CH1;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널2', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', CH2;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널3', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', CH3;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '채널4', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', CH4;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '단말연동일시', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', DEV_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '지번주소', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', JIBUN_ADDR;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '도로명주소', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', ROAD_ADDR;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '온도기록계작동여부', 'USER', DBO, 'TABLE', TB_CAR_NOREG_HIST, 'COLUMN', TEMP_YN;

DROP TABLE TB_AGENT_NOREG_HIST;

-- 미등록대리점이력
CREATE TABLE TB_AGENT_NOREG_HIST (
	  SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, CENTER_CD VARCHAR(5)
	, AGENT_CD VARCHAR(12) NOT NULL
	, DELI_NO VARCHAR(10) NOT NULL
	, DELI_DT DATETIME
	, TID1 VARCHAR(11)
	, TID2 VARCHAR(10)
, CONSTRAINT TB_AGENT_NOREG_HIST_PK PRIMARY KEY (
	SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량이력', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '납품번호', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', DELI_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '배송요청일', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', DELI_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '연동TID_1', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', TID1;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '연동TID_2', 'USER', DBO, 'TABLE', TB_AGENT_NOREG_HIST, 'COLUMN', TID2;

DROP TABLE TB_CSV_FILE;

-- 대용량엑셀파일
CREATE TABLE TB_CSV_FILE (
	  CSV_SEQ INT NOT NULL IDENTITY(0, 1)
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, STR_DATE DATE NOT NULL
	, END_DATE DATE
	, CENTER_CD VARCHAR(5) NOT NULL
	, FILE_NM VARCHAR(300)
	, FILE_SIZE INT
	, CNT INT
	, SAVE_FILE_NM VARCHAR(300)
	, SAVE_FILE_PATH VARCHAR(300)
	, DEL_YN VARCHAR(1) DEFAULT 'N'
	, DIV VARCHAR(10)
, CONSTRAINT TB_CSV_FILE_PK PRIMARY KEY (
	CSV_SEQ
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대용량엑셀파일', 'USER', DBO, 'TABLE', TB_CSV_FILE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '순번 (SEQ)', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', CSV_SEQ;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '시작일 (YYYYMMDD)', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', STR_DATE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '종료일 (YYYYMMDD)', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', END_DATE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일명 (원본파일명)', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', FILE_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일크기 (byte)', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', FILE_SIZE;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '건수', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', CNT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '저장파일명', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', SAVE_FILE_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '저장경로', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', SAVE_FILE_PATH;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '삭제여부 (Y:삭제, N:정상)', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', DEL_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '차량창고구분', 'USER', DBO, 'TABLE', TB_CSV_FILE, 'COLUMN', DIV;

DROP TABLE TB_AGENT_ALL;

-- 대리점정보
CREATE TABLE TB_AGENT_ALL (
	  AGENT_CD VARCHAR(12) NOT NULL
	, INSERT_DT DATETIME DEFAULT GETDATE() NOT NULL
	, INSERT_ID VARCHAR(20) NOT NULL
	, UPDATE_DT DATETIME
	, UPDATE_ID VARCHAR(20)
	, AGENT_NM VARCHAR(50)
	, USE_YN VARCHAR(1)
	, CENTER_CD VARCHAR(5)
	, EMP_NO VARCHAR(7)
	, SI VARCHAR(300)
	, GU VARCHAR(20)
	, DONG VARCHAR(20)
	, RI VARCHAR(50)
	, S_BUNJI VARCHAR(20)
	, E_BUNJI VARCHAR(20)
	, STAFF_NM VARCHAR(20)
	, STAFF_HP_NO VARCHAR(40)
	, STAFF_TEL_NO VARCHAR(40)
	, SO_CD VARCHAR(4)
	, CH_CD VARCHAR(3)
, CONSTRAINT TB_AGENT_ALL_PK PRIMARY KEY (
	AGENT_CD
  )
);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점정보', 'USER', DBO, 'TABLE', TB_AGENT_ALL;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점코드', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', AGENT_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록일시', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', INSERT_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '등록자', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', INSERT_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정일시', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', UPDATE_DT;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '수정자', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', UPDATE_ID;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점명 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', AGENT_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용여부 (사용여부 Y인것만 노출)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', USE_YN;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '센터코드 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', CENTER_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '담당사원사번 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', EMP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '시 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', SI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '구 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', GU;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '동 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', DONG;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '리 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', RI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '시작번지 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', S_BUNJI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '종료번지 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', E_BUNJI;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점장명 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', STAFF_NM;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점장휴대폰 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', STAFF_HP_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '대리점장전화번호 (수정불가)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', STAFF_TEL_NO;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사업장코드 (SO_CD; 1001, 1002…)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', SO_CD;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '영업그룹코드 (CH_CD; 112, 121, 122…)', 'USER', DBO, 'TABLE', TB_AGENT_ALL, 'COLUMN', CH_CD;


CREATE SEQUENCE [SQ_IF_ZSDS4103] AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE NO CACHE;
CREATE SEQUENCE [SQ_IF_ZSDS4104] AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE NO CACHE;

