DROP INDEX TB_CAR_HIST.TB_CAR_HIST_IDX1;
DROP INDEX TB_CAR_HIST.TB_CAR_NOREG_HIST_IDX1;
DROP INDEX TB_CAR_HIST.TB_CAR_NOREG_HIST_IDX2;
DROP INDEX TB_CAR_HIST.TB_AGENT_NOREG_HIST_IDX1;
DROP INDEX TB_CAR_HIST.TB_AGENT_NOREG_HIST_IDX2;
DROP INDEX TB_CARGO_HIST.TB_CARGO_HIST_IDX1;
DROP INDEX TB_CARGO_HIST.TB_CARGO_HIST_IDX2;
DROP INDEX TB_FILE.TB_FILE_IDX1;
DROP INDEX TB_CSV_FILE.TB_CSV_FILE_IDX1;

CREATE UNIQUE INDEX TB_CAR_HIST_IDX1 ON TB_CAR_HIST (LOG_DIV, CAR_ID, DEV_DT);
CREATE UNIQUE INDEX TB_CAR_NOREG_HIST_IDX1 ON TB_CAR_NOREG_HIST (LOG_DIV, CAR_TID, CAR_NO, DEV_DT);
CREATE INDEX TB_CAR_NOREG_HIST_IDX2 ON TB_CAR_NOREG_HIST (INSERT_DT);
CREATE UNIQUE INDEX TB_AGENT_NOREG_HIST_IDX1 ON TB_AGENT_NOREG_HIST (AGENT_CD, DELI_NO, DELI_DT);
CREATE INDEX TB_AGENT_NOREG_HIST_IDX2 ON TB_AGENT_NOREG_HIST (INSERT_DT);
CREATE INDEX TB_CARGO_HIST_IDX1 ON TB_CARGO_HIST (DEV_ID, DEV_DT);
CREATE UNIQUE INDEX TB_CARGO_HIST_IDX2 ON TB_CARGO_HIST (TID);
CREATE INDEX TB_FILE_IDX1 ON TB_FILE (FILE_KEY);
CREATE INDEX TB_CSV_FILE_IDX1 ON TB_CSV_FILE (STR_DATE);

DROP INDEX TB_DELI.TB_DELI_IDX1;
DROP INDEX TB_DELI_DTL.TB_DELI_DTL_IDX1;
DROP INDEX TB_AGENT.TB_AGENT_IDX1;

CREATE INDEX TB_DELI_IDX1 ON TB_DELI (SHIP_REQ_DATE);
CREATE INDEX TB_DELI_DTL_IDX1 ON TB_DELI_DTL (SHIP_NO, AGENT_CD, DELI_NO);
CREATE INDEX TB_AGENT_IDX1 ON TB_AGENT (CENTER_CD);


DROP INDEX TB_CAR.TB_CAR_IDX1;
DROP INDEX TB_CAR.TB_CAR_IDX2;
DROP INDEX TB_CAR_STAT.TB_CAR_STAT_IDX1;
DROP INDEX TB_CAR_STAT.TB_CAR_STAT_IDX2;
DROP INDEX TB_CAR_EVENT.TB_CAR_EVENT_IDX1;
DROP INDEX TB_CAR_EVENT.TB_CAR_EVENT_IDX2;
DROP INDEX TB_CARGO_DEV.TB_CARGO_DEV_IDX1;
DROP INDEX TB_CARGO_DEV.TB_CARGO_DEV_IDX2;
DROP INDEX TB_CARGO_STAT.TB_CARGO_STAT_IDX1;
DROP INDEX TB_CARGO_STAT.TB_CARGO_STAT_IDX2;

CREATE INDEX TB_CAR_IDX1 ON TB_CAR (CENTER_CD);
CREATE INDEX TB_CAR_IDX2 ON TB_CAR (AGENT_CD);
CREATE INDEX TB_CAR_STAT_IDX1 ON TB_CAR_STAT (CENTER_CD);
CREATE INDEX TB_CAR_STAT_IDX2 ON TB_CAR_STAT (AGENT_CD);
CREATE INDEX TB_CAR_EVENT_IDX1 ON TB_CAR_EVENT (CENTER_CD);
CREATE INDEX TB_CAR_EVENT_IDX2 ON TB_CAR_EVENT (AGENT_CD);
CREATE INDEX TB_CARGO_DEV_IDX1 ON TB_CARGO_DEV (CENTER_CD);
CREATE INDEX TB_CARGO_DEV_IDX2 ON TB_CARGO_DEV (AGENT_CD);
CREATE INDEX TB_CARGO_STAT_IDX1 ON TB_CARGO_STAT (CENTER_CD);
CREATE INDEX TB_CARGO_STAT_IDX2 ON TB_CARGO_STAT (AGENT_CD);
