/*경기*/
GRANT ALL ON	comtccmmnclcode	TO KRMA_APP;
GRANT ALL ON	comtccmmncode	TO KRMA_APP;
GRANT ALL ON	comtccmmndetailcode	TO KRMA_APP;
GRANT ALL ON	comtczip	TO KRMA_APP;
GRANT ALL ON	comtcnewzip	TO KRMA_APP;
GRANT ALL ON	krca_menu_mst	TO KRMA_APP;
GRANT ALL ON	krca_menu_sub	TO KRMA_APP;
GRANT ALL ON	krca_menu_author	TO KRMA_APP;
GRANT ALL ON	krca_doc_manager	TO KRMA_APP;
GRANT ALL ON	krca_civil_complaint_receipt	TO KRMA_APP;
GRANT ALL ON	comtnemplyrinfo	TO KRMA_APP;
GRANT ALL ON	comtnemplyrscrtyestbs	TO KRMA_APP;
GRANT ALL ON	krca_cust_company	TO KRMA_APP;
GRANT ALL ON	krca_cust_company_history	TO KRMA_APP;
GRANT ALL ON	krca_business_office	TO KRMA_APP;
GRANT ALL ON	krca_office_parking	TO KRMA_APP;
GRANT ALL ON	krca_business_office_history	TO KRMA_APP;
GRANT ALL ON	krca_reservation_place	TO KRMA_APP;
GRANT ALL ON	krca_reservation_parking	TO KRMA_APP;
GRANT ALL ON	krca_reservation_place_history	TO KRMA_APP;
GRANT ALL ON	krca_car_register	TO KRMA_APP;
GRANT ALL ON	krca_car_report	TO KRMA_APP;
GRANT ALL ON	krca_car_report_history	TO KRMA_APP;

/*서울*/
GRANT ALL ON	AGENT_CODE	TO KRMA_APP;
GRANT ALL ON	AGENT_CODE_D	TO KRMA_APP;
GRANT ALL ON	OFFICE_CODE	TO KRMA_APP;
GRANT ALL ON	OFFICE_HISTORY	TO KRMA_APP;
GRANT ALL ON	PUBLIC_HISTORY	TO KRMA_APP;
GRANT ALL ON	OFFICE_TEMP	TO KRMA_APP;
GRANT ALL ON	CHANGE_RESERVE	TO KRMA_APP;
GRANT ALL ON	CHANGER_CAR	TO KRMA_APP;
GRANT ALL ON	ZIP_NO	TO KRMA_APP;
GRANT ALL ON	USER_ID	TO KRMA_APP;
GRANT ALL ON	WORK_DSP	TO KRMA_APP;
GRANT ALL ON	WORK_INFO	TO KRMA_APP;
GRANT ALL ON	COMM_CODE	TO KRMA_APP;
GRANT ALL ON	CAR_KIND	TO KRMA_APP;
GRANT ALL ON	DOC010	TO KRMA_APP;
GRANT ALL ON	DOC020	TO KRMA_APP;

/*타유저 테이블 조회 수행*/
SELECT * FROM "dbo".AGENT_CODE;
SELECT * FROM MIG_GY.comtccmmnclcode;
REVOKE ALL ON AGENT_CODE TO KRMA_APP;

/* INSERT SELECT시 컬럼명 추출 */
SELECT SUBSTR(XMLAGG(XMLELEMENT(X, ', A.', COLUMN_NAME) ORDER BY COLUMN_ID).EXTRACT('//text()'), 3) AS COL_LIST FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'XBZZ1101';

--테이블 DROP전 백업테이블명으로 RENAME및 인덱스명 변경(추가 인덱스는 추가 작업 필요)
RENAME XBZZ1101 TO XBZZ1101_BAK;
ALTER TABLE XBZZ1101_BAK RENAME CONSTRAINT XBZZ1101_PK TO XBZZ1101_BAK_PK;
ALTER INDEX XBZZ1101_PK RENAME TO XBZZ1101_BAK_PK;

RENAME XBZZ1102 TO XBZZ1102_BAK;
ALTER TABLE XBZZ1102_BAK RENAME CONSTRAINT XBZZ1102_PK TO XBZZ1102_BAK_PK;
ALTER INDEX XBZZ1102_PK RENAME TO XBZZ1102_BAK_PK;

RENAME XBZZ1103 TO XBZZ1103_BAK;
ALTER TABLE XBZZ1103_BAK RENAME CONSTRAINT XBZZ1103_PK TO XBZZ1103_BAK_PK;
ALTER INDEX XBZZ1103_PK RENAME TO XBZZ1103_BAK_PK;

RENAME XBZZ9002 TO XBZZ9002_BAK;
ALTER TABLE XBZZ9002_BAK RENAME CONSTRAINT XBZZ9002_PK TO XBZZ9002_BAK_PK;
ALTER INDEX XBZZ9002_PK RENAME TO XBZZ9002_BAK_PK;


--테이블 DROP및 신규테이블 생성후 데이터 이전및 백업 테이블 삭제
INSERT INTO XBZZ1101
SELECT A.GRP_CD, A.GRP_CD_NM, A.APL_STR_DT, A.APL_END_DT, A.DEL_AT, A.FIRST_REG_DT, A.FIRST_REG_ID, A.LAST_UPD_DT, A.LAST_UPD_ID FROM XBZZ1101_BAK A;
DROP TABLE XBZZ1101_BAK;

INSERT INTO XBZZ1102
SELECT A.GRP_CD, A.TYPE_CD, A.DTL_CD, A.TYPE_CD_NM, A.DTL_CD_NM, A.SORT_SEQ, A.ETC_1, A.ETC_2, A.ETC_3, A.ETC_4, A.ETC_5, A.APL_STR_DT, A.APL_END_DT, A.USE_YN, A.DEL_AT, A.FIRST_REG_DT, A.FIRST_REG_ID, A.LAST_UPD_DT, A.LAST_UPD_ID FROM XBZZ1102_BAK A;
DROP TABLE XBZZ1102_BAK;

INSERT INTO XBZZ1103
SELECT A.MSG_ID, A.MSG_TYPE, A.MSG_BUSS_CD, A.MSG_NM, A.MSG_ETC, A.DEL_AT, A.FIRST_REG_DT, A.FIRST_REG_ID, A.LAST_UPD_DT, A.LAST_UPD_ID FROM XBZZ1103_BAK A;
DROP TABLE XBZZ1103_BAK;

INSERT INTO XBZZ9002
SELECT A.BATCH_KEY, A.BATCH_NM, A.BATCH_CLASS, A.BATCH_CYCLE, A.BATCH_STAT, A.BATCH_USE_YN, A.BATCH_GB, A.BATCH_LASTEXEC, A.BATCH_PARAM, A.BATCH_PARAMINFO, A.MIDDLE, A.SMALL, A.DEL_AT, A.FIRST_REG_DT, A.FIRST_REG_ID, A.LAST_UPD_DT, A.LAST_UPD_ID FROM XBZZ9002_BAK A;
DROP TABLE XBZZ9002_BAK;



